"""Diode plugin helpers."""

# Generated code. DO NOT EDIT.
# Timestamp: 2025-03-26 20:52:02Z

from dataclasses import dataclass
from typing import Type

from django.contrib.contenttypes.models import ContentType
from django.db import models


@dataclass
class RefInfo:
    object_type: str
    field_name: str
    is_generic: bool = False

_REF_INFO = {
    'ipam.asn': {
        'rir': RefInfo(object_type='ipam.rir', field_name='rir'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.asnrange': {
        'rir': RefInfo(object_type='ipam.rir', field_name='rir'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.aggregate': {
        'rir': RefInfo(object_type='ipam.rir', field_name='rir'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.cable': {
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.cabletermination': {
        'cable': RefInfo(object_type='dcim.cable', field_name='cable'),
        'terminationCircuitTermination': RefInfo(object_type='circuits.circuittermination', field_name='termination', is_generic=True),
        'terminationConsolePort': RefInfo(object_type='dcim.consoleport', field_name='termination', is_generic=True),
        'terminationConsoleServerPort': RefInfo(object_type='dcim.consoleserverport', field_name='termination', is_generic=True),
        'terminationFrontPort': RefInfo(object_type='dcim.frontport', field_name='termination', is_generic=True),
        'terminationInterface': RefInfo(object_type='dcim.interface', field_name='termination', is_generic=True),
        'terminationPowerFeed': RefInfo(object_type='dcim.powerfeed', field_name='termination', is_generic=True),
        'terminationPowerOutlet': RefInfo(object_type='dcim.poweroutlet', field_name='termination', is_generic=True),
        'terminationPowerPort': RefInfo(object_type='dcim.powerport', field_name='termination', is_generic=True),
        'terminationRearPort': RefInfo(object_type='dcim.rearport', field_name='termination', is_generic=True),
    },
    'circuits.circuit': {
        'provider': RefInfo(object_type='circuits.provider', field_name='provider'),
        'providerAccount': RefInfo(object_type='circuits.provideraccount', field_name='provider_account'),
        'type': RefInfo(object_type='circuits.circuittype', field_name='type'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
        'assignments': RefInfo(object_type='circuits.circuitgroupassignment', field_name='assignments'),
    },
    'circuits.circuitgroup': {
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'circuits.circuitgroupassignment': {
        'group': RefInfo(object_type='circuits.circuitgroup', field_name='group'),
        'memberCircuit': RefInfo(object_type='circuits.circuit', field_name='member', is_generic=True),
        'memberVirtualCircuit': RefInfo(object_type='circuits.virtualcircuit', field_name='member', is_generic=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'circuits.circuittermination': {
        'circuit': RefInfo(object_type='circuits.circuit', field_name='circuit'),
        'terminationLocation': RefInfo(object_type='dcim.location', field_name='termination', is_generic=True),
        'terminationProviderNetwork': RefInfo(object_type='circuits.providernetwork', field_name='termination', is_generic=True),
        'terminationRegion': RefInfo(object_type='dcim.region', field_name='termination', is_generic=True),
        'terminationSite': RefInfo(object_type='dcim.site', field_name='termination', is_generic=True),
        'terminationSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='termination', is_generic=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'circuits.circuittype': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'virtualization.cluster': {
        'type': RefInfo(object_type='virtualization.clustertype', field_name='type'),
        'group': RefInfo(object_type='virtualization.clustergroup', field_name='group'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'scopeLocation': RefInfo(object_type='dcim.location', field_name='scope', is_generic=True),
        'scopeRegion': RefInfo(object_type='dcim.region', field_name='scope', is_generic=True),
        'scopeSite': RefInfo(object_type='dcim.site', field_name='scope', is_generic=True),
        'scopeSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='scope', is_generic=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'virtualization.clustergroup': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'virtualization.clustertype': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.consoleport': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.consoleserverport': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'tenancy.contact': {
        'group': RefInfo(object_type='tenancy.contactgroup', field_name='group'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'tenancy.contactassignment': {
        'objectAsn': RefInfo(object_type='ipam.asn', field_name='object', is_generic=True),
        'objectAsnRange': RefInfo(object_type='ipam.asnrange', field_name='object', is_generic=True),
        'objectAggregate': RefInfo(object_type='ipam.aggregate', field_name='object', is_generic=True),
        'objectCable': RefInfo(object_type='dcim.cable', field_name='object', is_generic=True),
        'objectCablePath': RefInfo(object_type='dcim.cablepath', field_name='object', is_generic=True),
        'objectCableTermination': RefInfo(object_type='dcim.cabletermination', field_name='object', is_generic=True),
        'objectCircuit': RefInfo(object_type='circuits.circuit', field_name='object', is_generic=True),
        'objectCircuitGroup': RefInfo(object_type='circuits.circuitgroup', field_name='object', is_generic=True),
        'objectCircuitGroupAssignment': RefInfo(object_type='circuits.circuitgroupassignment', field_name='object', is_generic=True),
        'objectCircuitTermination': RefInfo(object_type='circuits.circuittermination', field_name='object', is_generic=True),
        'objectCircuitType': RefInfo(object_type='circuits.circuittype', field_name='object', is_generic=True),
        'objectCluster': RefInfo(object_type='virtualization.cluster', field_name='object', is_generic=True),
        'objectClusterGroup': RefInfo(object_type='virtualization.clustergroup', field_name='object', is_generic=True),
        'objectClusterType': RefInfo(object_type='virtualization.clustertype', field_name='object', is_generic=True),
        'objectConsolePort': RefInfo(object_type='dcim.consoleport', field_name='object', is_generic=True),
        'objectConsoleServerPort': RefInfo(object_type='dcim.consoleserverport', field_name='object', is_generic=True),
        'objectContact': RefInfo(object_type='tenancy.contact', field_name='object', is_generic=True),
        'objectContactAssignment': RefInfo(object_type='tenancy.contactassignment', field_name='object', is_generic=True),
        'objectContactGroup': RefInfo(object_type='tenancy.contactgroup', field_name='object', is_generic=True),
        'objectContactRole': RefInfo(object_type='tenancy.contactrole', field_name='object', is_generic=True),
        'objectDevice': RefInfo(object_type='dcim.device', field_name='object', is_generic=True),
        'objectDeviceBay': RefInfo(object_type='dcim.devicebay', field_name='object', is_generic=True),
        'objectDeviceRole': RefInfo(object_type='dcim.devicerole', field_name='object', is_generic=True),
        'objectDeviceType': RefInfo(object_type='dcim.devicetype', field_name='object', is_generic=True),
        'objectFhrpGroup': RefInfo(object_type='ipam.fhrpgroup', field_name='object', is_generic=True),
        'objectFhrpGroupAssignment': RefInfo(object_type='ipam.fhrpgroupassignment', field_name='object', is_generic=True),
        'objectFrontPort': RefInfo(object_type='dcim.frontport', field_name='object', is_generic=True),
        'objectIkePolicy': RefInfo(object_type='vpn.ikepolicy', field_name='object', is_generic=True),
        'objectIkeProposal': RefInfo(object_type='vpn.ikeproposal', field_name='object', is_generic=True),
        'objectIpAddress': RefInfo(object_type='ipam.ipaddress', field_name='object', is_generic=True),
        'objectIpRange': RefInfo(object_type='ipam.iprange', field_name='object', is_generic=True),
        'objectIpSecPolicy': RefInfo(object_type='vpn.ipsecpolicy', field_name='object', is_generic=True),
        'objectIpSecProfile': RefInfo(object_type='vpn.ipsecprofile', field_name='object', is_generic=True),
        'objectIpSecProposal': RefInfo(object_type='vpn.ipsecproposal', field_name='object', is_generic=True),
        'objectInterface': RefInfo(object_type='dcim.interface', field_name='object', is_generic=True),
        'objectInventoryItem': RefInfo(object_type='dcim.inventoryitem', field_name='object', is_generic=True),
        'objectInventoryItemRole': RefInfo(object_type='dcim.inventoryitemrole', field_name='object', is_generic=True),
        'objectL2Vpn': RefInfo(object_type='vpn.l2vpn', field_name='object', is_generic=True),
        'objectL2VpnTermination': RefInfo(object_type='vpn.l2vpntermination', field_name='object', is_generic=True),
        'objectLocation': RefInfo(object_type='dcim.location', field_name='object', is_generic=True),
        'objectMacAddress': RefInfo(object_type='dcim.macaddress', field_name='object', is_generic=True),
        'objectManufacturer': RefInfo(object_type='dcim.manufacturer', field_name='object', is_generic=True),
        'objectModule': RefInfo(object_type='dcim.module', field_name='object', is_generic=True),
        'objectModuleBay': RefInfo(object_type='dcim.modulebay', field_name='object', is_generic=True),
        'objectModuleType': RefInfo(object_type='dcim.moduletype', field_name='object', is_generic=True),
        'objectPlatform': RefInfo(object_type='dcim.platform', field_name='object', is_generic=True),
        'objectPowerFeed': RefInfo(object_type='dcim.powerfeed', field_name='object', is_generic=True),
        'objectPowerOutlet': RefInfo(object_type='dcim.poweroutlet', field_name='object', is_generic=True),
        'objectPowerPanel': RefInfo(object_type='dcim.powerpanel', field_name='object', is_generic=True),
        'objectPowerPort': RefInfo(object_type='dcim.powerport', field_name='object', is_generic=True),
        'objectPrefix': RefInfo(object_type='ipam.prefix', field_name='object', is_generic=True),
        'objectProvider': RefInfo(object_type='circuits.provider', field_name='object', is_generic=True),
        'objectProviderAccount': RefInfo(object_type='circuits.provideraccount', field_name='object', is_generic=True),
        'objectProviderNetwork': RefInfo(object_type='circuits.providernetwork', field_name='object', is_generic=True),
        'objectRir': RefInfo(object_type='ipam.rir', field_name='object', is_generic=True),
        'objectRack': RefInfo(object_type='dcim.rack', field_name='object', is_generic=True),
        'objectRackReservation': RefInfo(object_type='dcim.rackreservation', field_name='object', is_generic=True),
        'objectRackRole': RefInfo(object_type='dcim.rackrole', field_name='object', is_generic=True),
        'objectRackType': RefInfo(object_type='dcim.racktype', field_name='object', is_generic=True),
        'objectRearPort': RefInfo(object_type='dcim.rearport', field_name='object', is_generic=True),
        'objectRegion': RefInfo(object_type='dcim.region', field_name='object', is_generic=True),
        'objectRole': RefInfo(object_type='ipam.role', field_name='object', is_generic=True),
        'objectRouteTarget': RefInfo(object_type='ipam.routetarget', field_name='object', is_generic=True),
        'objectService': RefInfo(object_type='ipam.service', field_name='object', is_generic=True),
        'objectSite': RefInfo(object_type='dcim.site', field_name='object', is_generic=True),
        'objectSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='object', is_generic=True),
        'objectTag': RefInfo(object_type='extras.tag', field_name='object', is_generic=True),
        'objectTenant': RefInfo(object_type='tenancy.tenant', field_name='object', is_generic=True),
        'objectTenantGroup': RefInfo(object_type='tenancy.tenantgroup', field_name='object', is_generic=True),
        'objectTunnel': RefInfo(object_type='vpn.tunnel', field_name='object', is_generic=True),
        'objectTunnelGroup': RefInfo(object_type='vpn.tunnelgroup', field_name='object', is_generic=True),
        'objectTunnelTermination': RefInfo(object_type='vpn.tunneltermination', field_name='object', is_generic=True),
        'objectVlan': RefInfo(object_type='ipam.vlan', field_name='object', is_generic=True),
        'objectVlanGroup': RefInfo(object_type='ipam.vlangroup', field_name='object', is_generic=True),
        'objectVlanTranslationPolicy': RefInfo(object_type='ipam.vlantranslationpolicy', field_name='object', is_generic=True),
        'objectVlanTranslationRule': RefInfo(object_type='ipam.vlantranslationrule', field_name='object', is_generic=True),
        'objectVmInterface': RefInfo(object_type='virtualization.vminterface', field_name='object', is_generic=True),
        'objectVrf': RefInfo(object_type='ipam.vrf', field_name='object', is_generic=True),
        'objectVirtualChassis': RefInfo(object_type='dcim.virtualchassis', field_name='object', is_generic=True),
        'objectVirtualCircuit': RefInfo(object_type='circuits.virtualcircuit', field_name='object', is_generic=True),
        'objectVirtualCircuitTermination': RefInfo(object_type='circuits.virtualcircuittermination', field_name='object', is_generic=True),
        'objectVirtualCircuitType': RefInfo(object_type='circuits.virtualcircuittype', field_name='object', is_generic=True),
        'objectVirtualDeviceContext': RefInfo(object_type='dcim.virtualdevicecontext', field_name='object', is_generic=True),
        'objectVirtualDisk': RefInfo(object_type='virtualization.virtualdisk', field_name='object', is_generic=True),
        'objectVirtualMachine': RefInfo(object_type='virtualization.virtualmachine', field_name='object', is_generic=True),
        'objectWirelessLan': RefInfo(object_type='wireless.wirelesslan', field_name='object', is_generic=True),
        'objectWirelessLanGroup': RefInfo(object_type='wireless.wirelesslangroup', field_name='object', is_generic=True),
        'objectWirelessLink': RefInfo(object_type='wireless.wirelesslink', field_name='object', is_generic=True),
        'contact': RefInfo(object_type='tenancy.contact', field_name='contact'),
        'role': RefInfo(object_type='tenancy.contactrole', field_name='role'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'tenancy.contactgroup': {
        'parent': RefInfo(object_type='tenancy.contactgroup', field_name='parent'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'tenancy.contactrole': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.device': {
        'deviceType': RefInfo(object_type='dcim.devicetype', field_name='device_type'),
        'role': RefInfo(object_type='dcim.devicerole', field_name='role'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'platform': RefInfo(object_type='dcim.platform', field_name='platform'),
        'site': RefInfo(object_type='dcim.site', field_name='site'),
        'location': RefInfo(object_type='dcim.location', field_name='location'),
        'rack': RefInfo(object_type='dcim.rack', field_name='rack'),
        'primaryIp4': RefInfo(object_type='ipam.ipaddress', field_name='primary_ip4'),
        'primaryIp6': RefInfo(object_type='ipam.ipaddress', field_name='primary_ip6'),
        'oobIp': RefInfo(object_type='ipam.ipaddress', field_name='oob_ip'),
        'cluster': RefInfo(object_type='virtualization.cluster', field_name='cluster'),
        'virtualChassis': RefInfo(object_type='dcim.virtualchassis', field_name='virtual_chassis'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.devicebay': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'installedDevice': RefInfo(object_type='dcim.device', field_name='installed_device'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.devicerole': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.devicetype': {
        'manufacturer': RefInfo(object_type='dcim.manufacturer', field_name='manufacturer'),
        'defaultPlatform': RefInfo(object_type='dcim.platform', field_name='default_platform'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.fhrpgroup': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.fhrpgroupassignment': {
        'group': RefInfo(object_type='ipam.fhrpgroup', field_name='group'),
        'interfaceAsn': RefInfo(object_type='ipam.asn', field_name='interface', is_generic=True),
        'interfaceAsnRange': RefInfo(object_type='ipam.asnrange', field_name='interface', is_generic=True),
        'interfaceAggregate': RefInfo(object_type='ipam.aggregate', field_name='interface', is_generic=True),
        'interfaceCable': RefInfo(object_type='dcim.cable', field_name='interface', is_generic=True),
        'interfaceCablePath': RefInfo(object_type='dcim.cablepath', field_name='interface', is_generic=True),
        'interfaceCableTermination': RefInfo(object_type='dcim.cabletermination', field_name='interface', is_generic=True),
        'interfaceCircuit': RefInfo(object_type='circuits.circuit', field_name='interface', is_generic=True),
        'interfaceCircuitGroup': RefInfo(object_type='circuits.circuitgroup', field_name='interface', is_generic=True),
        'interfaceCircuitGroupAssignment': RefInfo(object_type='circuits.circuitgroupassignment', field_name='interface', is_generic=True),
        'interfaceCircuitTermination': RefInfo(object_type='circuits.circuittermination', field_name='interface', is_generic=True),
        'interfaceCircuitType': RefInfo(object_type='circuits.circuittype', field_name='interface', is_generic=True),
        'interfaceCluster': RefInfo(object_type='virtualization.cluster', field_name='interface', is_generic=True),
        'interfaceClusterGroup': RefInfo(object_type='virtualization.clustergroup', field_name='interface', is_generic=True),
        'interfaceClusterType': RefInfo(object_type='virtualization.clustertype', field_name='interface', is_generic=True),
        'interfaceConsolePort': RefInfo(object_type='dcim.consoleport', field_name='interface', is_generic=True),
        'interfaceConsoleServerPort': RefInfo(object_type='dcim.consoleserverport', field_name='interface', is_generic=True),
        'interfaceContact': RefInfo(object_type='tenancy.contact', field_name='interface', is_generic=True),
        'interfaceContactAssignment': RefInfo(object_type='tenancy.contactassignment', field_name='interface', is_generic=True),
        'interfaceContactGroup': RefInfo(object_type='tenancy.contactgroup', field_name='interface', is_generic=True),
        'interfaceContactRole': RefInfo(object_type='tenancy.contactrole', field_name='interface', is_generic=True),
        'interfaceDevice': RefInfo(object_type='dcim.device', field_name='interface', is_generic=True),
        'interfaceDeviceBay': RefInfo(object_type='dcim.devicebay', field_name='interface', is_generic=True),
        'interfaceDeviceRole': RefInfo(object_type='dcim.devicerole', field_name='interface', is_generic=True),
        'interfaceDeviceType': RefInfo(object_type='dcim.devicetype', field_name='interface', is_generic=True),
        'interfaceFhrpGroup': RefInfo(object_type='ipam.fhrpgroup', field_name='interface', is_generic=True),
        'interfaceFhrpGroupAssignment': RefInfo(object_type='ipam.fhrpgroupassignment', field_name='interface', is_generic=True),
        'interfaceFrontPort': RefInfo(object_type='dcim.frontport', field_name='interface', is_generic=True),
        'interfaceIkePolicy': RefInfo(object_type='vpn.ikepolicy', field_name='interface', is_generic=True),
        'interfaceIkeProposal': RefInfo(object_type='vpn.ikeproposal', field_name='interface', is_generic=True),
        'interfaceIpAddress': RefInfo(object_type='ipam.ipaddress', field_name='interface', is_generic=True),
        'interfaceIpRange': RefInfo(object_type='ipam.iprange', field_name='interface', is_generic=True),
        'interfaceIpSecPolicy': RefInfo(object_type='vpn.ipsecpolicy', field_name='interface', is_generic=True),
        'interfaceIpSecProfile': RefInfo(object_type='vpn.ipsecprofile', field_name='interface', is_generic=True),
        'interfaceIpSecProposal': RefInfo(object_type='vpn.ipsecproposal', field_name='interface', is_generic=True),
        'interfaceInterface': RefInfo(object_type='dcim.interface', field_name='interface', is_generic=True),
        'interfaceInventoryItem': RefInfo(object_type='dcim.inventoryitem', field_name='interface', is_generic=True),
        'interfaceInventoryItemRole': RefInfo(object_type='dcim.inventoryitemrole', field_name='interface', is_generic=True),
        'interfaceL2Vpn': RefInfo(object_type='vpn.l2vpn', field_name='interface', is_generic=True),
        'interfaceL2VpnTermination': RefInfo(object_type='vpn.l2vpntermination', field_name='interface', is_generic=True),
        'interfaceLocation': RefInfo(object_type='dcim.location', field_name='interface', is_generic=True),
        'interfaceMacAddress': RefInfo(object_type='dcim.macaddress', field_name='interface', is_generic=True),
        'interfaceManufacturer': RefInfo(object_type='dcim.manufacturer', field_name='interface', is_generic=True),
        'interfaceModule': RefInfo(object_type='dcim.module', field_name='interface', is_generic=True),
        'interfaceModuleBay': RefInfo(object_type='dcim.modulebay', field_name='interface', is_generic=True),
        'interfaceModuleType': RefInfo(object_type='dcim.moduletype', field_name='interface', is_generic=True),
        'interfacePlatform': RefInfo(object_type='dcim.platform', field_name='interface', is_generic=True),
        'interfacePowerFeed': RefInfo(object_type='dcim.powerfeed', field_name='interface', is_generic=True),
        'interfacePowerOutlet': RefInfo(object_type='dcim.poweroutlet', field_name='interface', is_generic=True),
        'interfacePowerPanel': RefInfo(object_type='dcim.powerpanel', field_name='interface', is_generic=True),
        'interfacePowerPort': RefInfo(object_type='dcim.powerport', field_name='interface', is_generic=True),
        'interfacePrefix': RefInfo(object_type='ipam.prefix', field_name='interface', is_generic=True),
        'interfaceProvider': RefInfo(object_type='circuits.provider', field_name='interface', is_generic=True),
        'interfaceProviderAccount': RefInfo(object_type='circuits.provideraccount', field_name='interface', is_generic=True),
        'interfaceProviderNetwork': RefInfo(object_type='circuits.providernetwork', field_name='interface', is_generic=True),
        'interfaceRir': RefInfo(object_type='ipam.rir', field_name='interface', is_generic=True),
        'interfaceRack': RefInfo(object_type='dcim.rack', field_name='interface', is_generic=True),
        'interfaceRackReservation': RefInfo(object_type='dcim.rackreservation', field_name='interface', is_generic=True),
        'interfaceRackRole': RefInfo(object_type='dcim.rackrole', field_name='interface', is_generic=True),
        'interfaceRackType': RefInfo(object_type='dcim.racktype', field_name='interface', is_generic=True),
        'interfaceRearPort': RefInfo(object_type='dcim.rearport', field_name='interface', is_generic=True),
        'interfaceRegion': RefInfo(object_type='dcim.region', field_name='interface', is_generic=True),
        'interfaceRole': RefInfo(object_type='ipam.role', field_name='interface', is_generic=True),
        'interfaceRouteTarget': RefInfo(object_type='ipam.routetarget', field_name='interface', is_generic=True),
        'interfaceService': RefInfo(object_type='ipam.service', field_name='interface', is_generic=True),
        'interfaceSite': RefInfo(object_type='dcim.site', field_name='interface', is_generic=True),
        'interfaceSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='interface', is_generic=True),
        'interfaceTag': RefInfo(object_type='extras.tag', field_name='interface', is_generic=True),
        'interfaceTenant': RefInfo(object_type='tenancy.tenant', field_name='interface', is_generic=True),
        'interfaceTenantGroup': RefInfo(object_type='tenancy.tenantgroup', field_name='interface', is_generic=True),
        'interfaceTunnel': RefInfo(object_type='vpn.tunnel', field_name='interface', is_generic=True),
        'interfaceTunnelGroup': RefInfo(object_type='vpn.tunnelgroup', field_name='interface', is_generic=True),
        'interfaceTunnelTermination': RefInfo(object_type='vpn.tunneltermination', field_name='interface', is_generic=True),
        'interfaceVlan': RefInfo(object_type='ipam.vlan', field_name='interface', is_generic=True),
        'interfaceVlanGroup': RefInfo(object_type='ipam.vlangroup', field_name='interface', is_generic=True),
        'interfaceVlanTranslationPolicy': RefInfo(object_type='ipam.vlantranslationpolicy', field_name='interface', is_generic=True),
        'interfaceVlanTranslationRule': RefInfo(object_type='ipam.vlantranslationrule', field_name='interface', is_generic=True),
        'interfaceVmInterface': RefInfo(object_type='virtualization.vminterface', field_name='interface', is_generic=True),
        'interfaceVrf': RefInfo(object_type='ipam.vrf', field_name='interface', is_generic=True),
        'interfaceVirtualChassis': RefInfo(object_type='dcim.virtualchassis', field_name='interface', is_generic=True),
        'interfaceVirtualCircuit': RefInfo(object_type='circuits.virtualcircuit', field_name='interface', is_generic=True),
        'interfaceVirtualCircuitTermination': RefInfo(object_type='circuits.virtualcircuittermination', field_name='interface', is_generic=True),
        'interfaceVirtualCircuitType': RefInfo(object_type='circuits.virtualcircuittype', field_name='interface', is_generic=True),
        'interfaceVirtualDeviceContext': RefInfo(object_type='dcim.virtualdevicecontext', field_name='interface', is_generic=True),
        'interfaceVirtualDisk': RefInfo(object_type='virtualization.virtualdisk', field_name='interface', is_generic=True),
        'interfaceVirtualMachine': RefInfo(object_type='virtualization.virtualmachine', field_name='interface', is_generic=True),
        'interfaceWirelessLan': RefInfo(object_type='wireless.wirelesslan', field_name='interface', is_generic=True),
        'interfaceWirelessLanGroup': RefInfo(object_type='wireless.wirelesslangroup', field_name='interface', is_generic=True),
        'interfaceWirelessLink': RefInfo(object_type='wireless.wirelesslink', field_name='interface', is_generic=True),
    },
    'dcim.frontport': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'rearPort': RefInfo(object_type='dcim.rearport', field_name='rear_port'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'vpn.ikepolicy': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'vpn.ikeproposal': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.ipaddress': {
        'vrf': RefInfo(object_type='ipam.vrf', field_name='vrf'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'assignedObjectFhrpGroup': RefInfo(object_type='ipam.fhrpgroup', field_name='assigned_object', is_generic=True),
        'assignedObjectInterface': RefInfo(object_type='dcim.interface', field_name='assigned_object', is_generic=True),
        'assignedObjectVmInterface': RefInfo(object_type='virtualization.vminterface', field_name='assigned_object', is_generic=True),
        'natInside': RefInfo(object_type='ipam.ipaddress', field_name='nat_inside'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.iprange': {
        'vrf': RefInfo(object_type='ipam.vrf', field_name='vrf'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'role': RefInfo(object_type='ipam.role', field_name='role'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'vpn.ipsecpolicy': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'vpn.ipsecprofile': {
        'ikePolicy': RefInfo(object_type='vpn.ikepolicy', field_name='ike_policy'),
        'ipsecPolicy': RefInfo(object_type='vpn.ipsecpolicy', field_name='ipsec_policy'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'vpn.ipsecproposal': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.interface': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'parent': RefInfo(object_type='dcim.interface', field_name='parent'),
        'bridge': RefInfo(object_type='dcim.interface', field_name='bridge'),
        'lag': RefInfo(object_type='dcim.interface', field_name='lag'),
        'primaryMacAddress': RefInfo(object_type='dcim.macaddress', field_name='primary_mac_address'),
        'untaggedVlan': RefInfo(object_type='ipam.vlan', field_name='untagged_vlan'),
        'qinqSvlan': RefInfo(object_type='ipam.vlan', field_name='qinq_svlan'),
        'vlanTranslationPolicy': RefInfo(object_type='ipam.vlantranslationpolicy', field_name='vlan_translation_policy'),
        'vrf': RefInfo(object_type='ipam.vrf', field_name='vrf'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.inventoryitem': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'parent': RefInfo(object_type='dcim.inventoryitem', field_name='parent'),
        'role': RefInfo(object_type='dcim.inventoryitemrole', field_name='role'),
        'manufacturer': RefInfo(object_type='dcim.manufacturer', field_name='manufacturer'),
        'componentConsolePort': RefInfo(object_type='dcim.consoleport', field_name='component', is_generic=True),
        'componentConsoleServerPort': RefInfo(object_type='dcim.consoleserverport', field_name='component', is_generic=True),
        'componentFrontPort': RefInfo(object_type='dcim.frontport', field_name='component', is_generic=True),
        'componentInterface': RefInfo(object_type='dcim.interface', field_name='component', is_generic=True),
        'componentPowerOutlet': RefInfo(object_type='dcim.poweroutlet', field_name='component', is_generic=True),
        'componentPowerPort': RefInfo(object_type='dcim.powerport', field_name='component', is_generic=True),
        'componentRearPort': RefInfo(object_type='dcim.rearport', field_name='component', is_generic=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.inventoryitemrole': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'vpn.l2vpn': {
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'vpn.l2vpntermination': {
        'l2Vpn': RefInfo(object_type='vpn.l2vpn', field_name='l2vpn'),
        'assignedObjectInterface': RefInfo(object_type='dcim.interface', field_name='assigned_object', is_generic=True),
        'assignedObjectVlan': RefInfo(object_type='ipam.vlan', field_name='assigned_object', is_generic=True),
        'assignedObjectVmInterface': RefInfo(object_type='virtualization.vminterface', field_name='assigned_object', is_generic=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.location': {
        'site': RefInfo(object_type='dcim.site', field_name='site'),
        'parent': RefInfo(object_type='dcim.location', field_name='parent'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.macaddress': {
        'assignedObjectInterface': RefInfo(object_type='dcim.interface', field_name='assigned_object', is_generic=True),
        'assignedObjectVmInterface': RefInfo(object_type='virtualization.vminterface', field_name='assigned_object', is_generic=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.manufacturer': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.module': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'moduleBay': RefInfo(object_type='dcim.modulebay', field_name='module_bay'),
        'moduleType': RefInfo(object_type='dcim.moduletype', field_name='module_type'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.modulebay': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'installedModule': RefInfo(object_type='dcim.module', field_name='installed_module'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.moduletype': {
        'manufacturer': RefInfo(object_type='dcim.manufacturer', field_name='manufacturer'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.platform': {
        'manufacturer': RefInfo(object_type='dcim.manufacturer', field_name='manufacturer'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.powerfeed': {
        'powerPanel': RefInfo(object_type='dcim.powerpanel', field_name='power_panel'),
        'rack': RefInfo(object_type='dcim.rack', field_name='rack'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.poweroutlet': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'powerPort': RefInfo(object_type='dcim.powerport', field_name='power_port'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.powerpanel': {
        'site': RefInfo(object_type='dcim.site', field_name='site'),
        'location': RefInfo(object_type='dcim.location', field_name='location'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.powerport': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.prefix': {
        'vrf': RefInfo(object_type='ipam.vrf', field_name='vrf'),
        'scopeLocation': RefInfo(object_type='dcim.location', field_name='scope', is_generic=True),
        'scopeRegion': RefInfo(object_type='dcim.region', field_name='scope', is_generic=True),
        'scopeSite': RefInfo(object_type='dcim.site', field_name='scope', is_generic=True),
        'scopeSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='scope', is_generic=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'vlan': RefInfo(object_type='ipam.vlan', field_name='vlan'),
        'role': RefInfo(object_type='ipam.role', field_name='role'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'circuits.provider': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'circuits.provideraccount': {
        'provider': RefInfo(object_type='circuits.provider', field_name='provider'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'circuits.providernetwork': {
        'provider': RefInfo(object_type='circuits.provider', field_name='provider'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.rir': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.rack': {
        'site': RefInfo(object_type='dcim.site', field_name='site'),
        'location': RefInfo(object_type='dcim.location', field_name='location'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'role': RefInfo(object_type='dcim.rackrole', field_name='role'),
        'rackType': RefInfo(object_type='dcim.racktype', field_name='rack_type'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.rackreservation': {
        'rack': RefInfo(object_type='dcim.rack', field_name='rack'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.rackrole': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.racktype': {
        'manufacturer': RefInfo(object_type='dcim.manufacturer', field_name='manufacturer'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.rearport': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.region': {
        'parent': RefInfo(object_type='dcim.region', field_name='parent'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.role': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.routetarget': {
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.service': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'virtualMachine': RefInfo(object_type='virtualization.virtualmachine', field_name='virtual_machine'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.site': {
        'region': RefInfo(object_type='dcim.region', field_name='region'),
        'group': RefInfo(object_type='dcim.sitegroup', field_name='group'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.sitegroup': {
        'parent': RefInfo(object_type='dcim.sitegroup', field_name='parent'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'tenancy.tenant': {
        'group': RefInfo(object_type='tenancy.tenantgroup', field_name='group'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'tenancy.tenantgroup': {
        'parent': RefInfo(object_type='tenancy.tenantgroup', field_name='parent'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'vpn.tunnel': {
        'group': RefInfo(object_type='vpn.tunnelgroup', field_name='group'),
        'ipsecProfile': RefInfo(object_type='vpn.ipsecprofile', field_name='ipsec_profile'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'vpn.tunnelgroup': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'vpn.tunneltermination': {
        'tunnel': RefInfo(object_type='vpn.tunnel', field_name='tunnel'),
        'terminationAsn': RefInfo(object_type='ipam.asn', field_name='termination', is_generic=True),
        'terminationAsnRange': RefInfo(object_type='ipam.asnrange', field_name='termination', is_generic=True),
        'terminationAggregate': RefInfo(object_type='ipam.aggregate', field_name='termination', is_generic=True),
        'terminationCable': RefInfo(object_type='dcim.cable', field_name='termination', is_generic=True),
        'terminationCablePath': RefInfo(object_type='dcim.cablepath', field_name='termination', is_generic=True),
        'terminationCableTermination': RefInfo(object_type='dcim.cabletermination', field_name='termination', is_generic=True),
        'terminationCircuit': RefInfo(object_type='circuits.circuit', field_name='termination', is_generic=True),
        'terminationCircuitGroup': RefInfo(object_type='circuits.circuitgroup', field_name='termination', is_generic=True),
        'terminationCircuitGroupAssignment': RefInfo(object_type='circuits.circuitgroupassignment', field_name='termination', is_generic=True),
        'terminationCircuitTermination': RefInfo(object_type='circuits.circuittermination', field_name='termination', is_generic=True),
        'terminationCircuitType': RefInfo(object_type='circuits.circuittype', field_name='termination', is_generic=True),
        'terminationCluster': RefInfo(object_type='virtualization.cluster', field_name='termination', is_generic=True),
        'terminationClusterGroup': RefInfo(object_type='virtualization.clustergroup', field_name='termination', is_generic=True),
        'terminationClusterType': RefInfo(object_type='virtualization.clustertype', field_name='termination', is_generic=True),
        'terminationConsolePort': RefInfo(object_type='dcim.consoleport', field_name='termination', is_generic=True),
        'terminationConsoleServerPort': RefInfo(object_type='dcim.consoleserverport', field_name='termination', is_generic=True),
        'terminationContact': RefInfo(object_type='tenancy.contact', field_name='termination', is_generic=True),
        'terminationContactAssignment': RefInfo(object_type='tenancy.contactassignment', field_name='termination', is_generic=True),
        'terminationContactGroup': RefInfo(object_type='tenancy.contactgroup', field_name='termination', is_generic=True),
        'terminationContactRole': RefInfo(object_type='tenancy.contactrole', field_name='termination', is_generic=True),
        'terminationDevice': RefInfo(object_type='dcim.device', field_name='termination', is_generic=True),
        'terminationDeviceBay': RefInfo(object_type='dcim.devicebay', field_name='termination', is_generic=True),
        'terminationDeviceRole': RefInfo(object_type='dcim.devicerole', field_name='termination', is_generic=True),
        'terminationDeviceType': RefInfo(object_type='dcim.devicetype', field_name='termination', is_generic=True),
        'terminationFhrpGroup': RefInfo(object_type='ipam.fhrpgroup', field_name='termination', is_generic=True),
        'terminationFhrpGroupAssignment': RefInfo(object_type='ipam.fhrpgroupassignment', field_name='termination', is_generic=True),
        'terminationFrontPort': RefInfo(object_type='dcim.frontport', field_name='termination', is_generic=True),
        'terminationIkePolicy': RefInfo(object_type='vpn.ikepolicy', field_name='termination', is_generic=True),
        'terminationIkeProposal': RefInfo(object_type='vpn.ikeproposal', field_name='termination', is_generic=True),
        'terminationIpAddress': RefInfo(object_type='ipam.ipaddress', field_name='termination', is_generic=True),
        'terminationIpRange': RefInfo(object_type='ipam.iprange', field_name='termination', is_generic=True),
        'terminationIpSecPolicy': RefInfo(object_type='vpn.ipsecpolicy', field_name='termination', is_generic=True),
        'terminationIpSecProfile': RefInfo(object_type='vpn.ipsecprofile', field_name='termination', is_generic=True),
        'terminationIpSecProposal': RefInfo(object_type='vpn.ipsecproposal', field_name='termination', is_generic=True),
        'terminationInterface': RefInfo(object_type='dcim.interface', field_name='termination', is_generic=True),
        'terminationInventoryItem': RefInfo(object_type='dcim.inventoryitem', field_name='termination', is_generic=True),
        'terminationInventoryItemRole': RefInfo(object_type='dcim.inventoryitemrole', field_name='termination', is_generic=True),
        'terminationL2Vpn': RefInfo(object_type='vpn.l2vpn', field_name='termination', is_generic=True),
        'terminationL2VpnTermination': RefInfo(object_type='vpn.l2vpntermination', field_name='termination', is_generic=True),
        'terminationLocation': RefInfo(object_type='dcim.location', field_name='termination', is_generic=True),
        'terminationMacAddress': RefInfo(object_type='dcim.macaddress', field_name='termination', is_generic=True),
        'terminationManufacturer': RefInfo(object_type='dcim.manufacturer', field_name='termination', is_generic=True),
        'terminationModule': RefInfo(object_type='dcim.module', field_name='termination', is_generic=True),
        'terminationModuleBay': RefInfo(object_type='dcim.modulebay', field_name='termination', is_generic=True),
        'terminationModuleType': RefInfo(object_type='dcim.moduletype', field_name='termination', is_generic=True),
        'terminationPlatform': RefInfo(object_type='dcim.platform', field_name='termination', is_generic=True),
        'terminationPowerFeed': RefInfo(object_type='dcim.powerfeed', field_name='termination', is_generic=True),
        'terminationPowerOutlet': RefInfo(object_type='dcim.poweroutlet', field_name='termination', is_generic=True),
        'terminationPowerPanel': RefInfo(object_type='dcim.powerpanel', field_name='termination', is_generic=True),
        'terminationPowerPort': RefInfo(object_type='dcim.powerport', field_name='termination', is_generic=True),
        'terminationPrefix': RefInfo(object_type='ipam.prefix', field_name='termination', is_generic=True),
        'terminationProvider': RefInfo(object_type='circuits.provider', field_name='termination', is_generic=True),
        'terminationProviderAccount': RefInfo(object_type='circuits.provideraccount', field_name='termination', is_generic=True),
        'terminationProviderNetwork': RefInfo(object_type='circuits.providernetwork', field_name='termination', is_generic=True),
        'terminationRir': RefInfo(object_type='ipam.rir', field_name='termination', is_generic=True),
        'terminationRack': RefInfo(object_type='dcim.rack', field_name='termination', is_generic=True),
        'terminationRackReservation': RefInfo(object_type='dcim.rackreservation', field_name='termination', is_generic=True),
        'terminationRackRole': RefInfo(object_type='dcim.rackrole', field_name='termination', is_generic=True),
        'terminationRackType': RefInfo(object_type='dcim.racktype', field_name='termination', is_generic=True),
        'terminationRearPort': RefInfo(object_type='dcim.rearport', field_name='termination', is_generic=True),
        'terminationRegion': RefInfo(object_type='dcim.region', field_name='termination', is_generic=True),
        'terminationRole': RefInfo(object_type='ipam.role', field_name='termination', is_generic=True),
        'terminationRouteTarget': RefInfo(object_type='ipam.routetarget', field_name='termination', is_generic=True),
        'terminationService': RefInfo(object_type='ipam.service', field_name='termination', is_generic=True),
        'terminationSite': RefInfo(object_type='dcim.site', field_name='termination', is_generic=True),
        'terminationSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='termination', is_generic=True),
        'terminationTag': RefInfo(object_type='extras.tag', field_name='termination', is_generic=True),
        'terminationTenant': RefInfo(object_type='tenancy.tenant', field_name='termination', is_generic=True),
        'terminationTenantGroup': RefInfo(object_type='tenancy.tenantgroup', field_name='termination', is_generic=True),
        'terminationTunnel': RefInfo(object_type='vpn.tunnel', field_name='termination', is_generic=True),
        'terminationTunnelGroup': RefInfo(object_type='vpn.tunnelgroup', field_name='termination', is_generic=True),
        'terminationTunnelTermination': RefInfo(object_type='vpn.tunneltermination', field_name='termination', is_generic=True),
        'terminationVlan': RefInfo(object_type='ipam.vlan', field_name='termination', is_generic=True),
        'terminationVlanGroup': RefInfo(object_type='ipam.vlangroup', field_name='termination', is_generic=True),
        'terminationVlanTranslationPolicy': RefInfo(object_type='ipam.vlantranslationpolicy', field_name='termination', is_generic=True),
        'terminationVlanTranslationRule': RefInfo(object_type='ipam.vlantranslationrule', field_name='termination', is_generic=True),
        'terminationVmInterface': RefInfo(object_type='virtualization.vminterface', field_name='termination', is_generic=True),
        'terminationVrf': RefInfo(object_type='ipam.vrf', field_name='termination', is_generic=True),
        'terminationVirtualChassis': RefInfo(object_type='dcim.virtualchassis', field_name='termination', is_generic=True),
        'terminationVirtualCircuit': RefInfo(object_type='circuits.virtualcircuit', field_name='termination', is_generic=True),
        'terminationVirtualCircuitTermination': RefInfo(object_type='circuits.virtualcircuittermination', field_name='termination', is_generic=True),
        'terminationVirtualCircuitType': RefInfo(object_type='circuits.virtualcircuittype', field_name='termination', is_generic=True),
        'terminationVirtualDeviceContext': RefInfo(object_type='dcim.virtualdevicecontext', field_name='termination', is_generic=True),
        'terminationVirtualDisk': RefInfo(object_type='virtualization.virtualdisk', field_name='termination', is_generic=True),
        'terminationVirtualMachine': RefInfo(object_type='virtualization.virtualmachine', field_name='termination', is_generic=True),
        'terminationWirelessLan': RefInfo(object_type='wireless.wirelesslan', field_name='termination', is_generic=True),
        'terminationWirelessLanGroup': RefInfo(object_type='wireless.wirelesslangroup', field_name='termination', is_generic=True),
        'terminationWirelessLink': RefInfo(object_type='wireless.wirelesslink', field_name='termination', is_generic=True),
        'outsideIp': RefInfo(object_type='ipam.ipaddress', field_name='outside_ip'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.vlan': {
        'site': RefInfo(object_type='dcim.site', field_name='site'),
        'group': RefInfo(object_type='ipam.vlangroup', field_name='group'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'role': RefInfo(object_type='ipam.role', field_name='role'),
        'qinqSvlan': RefInfo(object_type='ipam.vlan', field_name='qinq_svlan'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.vlangroup': {
        'scopeCluster': RefInfo(object_type='virtualization.cluster', field_name='scope', is_generic=True),
        'scopeClusterGroup': RefInfo(object_type='virtualization.clustergroup', field_name='scope', is_generic=True),
        'scopeLocation': RefInfo(object_type='dcim.location', field_name='scope', is_generic=True),
        'scopeRack': RefInfo(object_type='dcim.rack', field_name='scope', is_generic=True),
        'scopeRegion': RefInfo(object_type='dcim.region', field_name='scope', is_generic=True),
        'scopeSite': RefInfo(object_type='dcim.site', field_name='scope', is_generic=True),
        'scopeSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='scope', is_generic=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.vlantranslationrule': {
        'policy': RefInfo(object_type='ipam.vlantranslationpolicy', field_name='policy'),
    },
    'virtualization.vminterface': {
        'virtualMachine': RefInfo(object_type='virtualization.virtualmachine', field_name='virtual_machine'),
        'parent': RefInfo(object_type='virtualization.vminterface', field_name='parent'),
        'bridge': RefInfo(object_type='virtualization.vminterface', field_name='bridge'),
        'primaryMacAddress': RefInfo(object_type='dcim.macaddress', field_name='primary_mac_address'),
        'untaggedVlan': RefInfo(object_type='ipam.vlan', field_name='untagged_vlan'),
        'qinqSvlan': RefInfo(object_type='ipam.vlan', field_name='qinq_svlan'),
        'vlanTranslationPolicy': RefInfo(object_type='ipam.vlantranslationpolicy', field_name='vlan_translation_policy'),
        'vrf': RefInfo(object_type='ipam.vrf', field_name='vrf'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'ipam.vrf': {
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.virtualchassis': {
        'master': RefInfo(object_type='dcim.device', field_name='master'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'circuits.virtualcircuit': {
        'providerNetwork': RefInfo(object_type='circuits.providernetwork', field_name='provider_network'),
        'providerAccount': RefInfo(object_type='circuits.provideraccount', field_name='provider_account'),
        'type': RefInfo(object_type='circuits.virtualcircuittype', field_name='type'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'circuits.virtualcircuittermination': {
        'virtualCircuit': RefInfo(object_type='circuits.virtualcircuit', field_name='virtual_circuit'),
        'interface': RefInfo(object_type='dcim.interface', field_name='interface'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'circuits.virtualcircuittype': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'dcim.virtualdevicecontext': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'primaryIp4': RefInfo(object_type='ipam.ipaddress', field_name='primary_ip4'),
        'primaryIp6': RefInfo(object_type='ipam.ipaddress', field_name='primary_ip6'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'virtualization.virtualdisk': {
        'virtualMachine': RefInfo(object_type='virtualization.virtualmachine', field_name='virtual_machine'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'virtualization.virtualmachine': {
        'site': RefInfo(object_type='dcim.site', field_name='site'),
        'cluster': RefInfo(object_type='virtualization.cluster', field_name='cluster'),
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'role': RefInfo(object_type='dcim.devicerole', field_name='role'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'platform': RefInfo(object_type='dcim.platform', field_name='platform'),
        'primaryIp4': RefInfo(object_type='ipam.ipaddress', field_name='primary_ip4'),
        'primaryIp6': RefInfo(object_type='ipam.ipaddress', field_name='primary_ip6'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'wireless.wirelesslan': {
        'group': RefInfo(object_type='wireless.wirelesslangroup', field_name='group'),
        'vlan': RefInfo(object_type='ipam.vlan', field_name='vlan'),
        'scopeLocation': RefInfo(object_type='dcim.location', field_name='scope', is_generic=True),
        'scopeRegion': RefInfo(object_type='dcim.region', field_name='scope', is_generic=True),
        'scopeSite': RefInfo(object_type='dcim.site', field_name='scope', is_generic=True),
        'scopeSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='scope', is_generic=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'wireless.wirelesslangroup': {
        'parent': RefInfo(object_type='wireless.wirelesslangroup', field_name='parent'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
    'wireless.wirelesslink': {
        'interfaceA': RefInfo(object_type='dcim.interface', field_name='interface_a'),
        'interfaceB': RefInfo(object_type='dcim.interface', field_name='interface_b'),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags'),
    },
}

def get_json_ref_info(object_type: str|Type[models.Model], json_field_name: str) -> RefInfo|None:
    if isinstance(object_type, models.Model):
        content_type = ContentType.objects.get_for_model(object_type)
        object_type = content_type.app_label + '.' + content_type.model
    return _REF_INFO.get(object_type, {}).get(json_field_name)
