"""Diode plugin helpers."""

# Generated code. DO NOT EDIT.
# Timestamp: 2025-04-01 21:05:16Z

from dataclasses import dataclass
from functools import lru_cache
from typing import Type

from core.models import ObjectType as NetBoxType
from django.contrib.contenttypes.models import ContentType
from django.db import models


@lru_cache(maxsize=256)
def get_object_type_model(object_type: str) -> Type[models.Model]:
    """Get the model class for a given object type."""
    app_label, model_name = object_type.split('.')
    object_content_type = NetBoxType.objects.get_by_natural_key(app_label, model_name)
    return object_content_type.model_class()

@lru_cache(maxsize=256)
def get_object_type(model_class: Type[models.Model]) -> str:
    """Get the object type for a given model class."""
    content_type = ContentType.objects.get_for_model(model_class)
    return content_type.app_label + '.' + content_type.model

@lru_cache(maxsize=256)
def content_type_id(object_type: str) -> int:
    """Get the content type id for a given object type."""
    app_label, model_name = object_type.split('.')
    object_content_type = NetBoxType.objects.get_by_natural_key(app_label, model_name)
    return object_content_type.id

@dataclass
class RefInfo:
    object_type: str
    field_name: str
    is_generic: bool = False
    is_many: bool = False

_JSON_REF_INFO = {
    'circuits.circuit': {
        'assignments': RefInfo(object_type='circuits.circuitgroupassignment', field_name='assignments', is_many=True),
        'provider': RefInfo(object_type='circuits.provider', field_name='provider'),
        'providerAccount': RefInfo(object_type='circuits.provideraccount', field_name='provider_account'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'type': RefInfo(object_type='circuits.circuittype', field_name='type'),
    },
    'circuits.circuitgroup': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'circuits.circuitgroupassignment': {
        'group': RefInfo(object_type='circuits.circuitgroup', field_name='group'),
        'memberCircuit': RefInfo(object_type='circuits.circuit', field_name='member', is_generic=True),
        'memberVirtualCircuit': RefInfo(object_type='circuits.virtualcircuit', field_name='member', is_generic=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'circuits.circuittermination': {
        'circuit': RefInfo(object_type='circuits.circuit', field_name='circuit'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'terminationLocation': RefInfo(object_type='dcim.location', field_name='termination', is_generic=True),
        'terminationProviderNetwork': RefInfo(object_type='circuits.providernetwork', field_name='termination', is_generic=True),
        'terminationRegion': RefInfo(object_type='dcim.region', field_name='termination', is_generic=True),
        'terminationSite': RefInfo(object_type='dcim.site', field_name='termination', is_generic=True),
        'terminationSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='termination', is_generic=True),
    },
    'circuits.circuittype': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'circuits.provider': {
        'accounts': RefInfo(object_type='circuits.provideraccount', field_name='accounts', is_many=True),
        'asns': RefInfo(object_type='ipam.asn', field_name='asns', is_many=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'circuits.provideraccount': {
        'provider': RefInfo(object_type='circuits.provider', field_name='provider'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'circuits.providernetwork': {
        'provider': RefInfo(object_type='circuits.provider', field_name='provider'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'circuits.virtualcircuit': {
        'providerAccount': RefInfo(object_type='circuits.provideraccount', field_name='provider_account'),
        'providerNetwork': RefInfo(object_type='circuits.providernetwork', field_name='provider_network'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'type': RefInfo(object_type='circuits.virtualcircuittype', field_name='type'),
    },
    'circuits.virtualcircuittermination': {
        'interface': RefInfo(object_type='dcim.interface', field_name='interface'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'virtualCircuit': RefInfo(object_type='circuits.virtualcircuit', field_name='virtual_circuit'),
    },
    'circuits.virtualcircuittype': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.cable': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'dcim.cabletermination': {
        'cable': RefInfo(object_type='dcim.cable', field_name='cable'),
        'terminationCircuitTermination': RefInfo(object_type='circuits.circuittermination', field_name='termination', is_generic=True),
        'terminationConsolePort': RefInfo(object_type='dcim.consoleport', field_name='termination', is_generic=True),
        'terminationConsoleServerPort': RefInfo(object_type='dcim.consoleserverport', field_name='termination', is_generic=True),
        'terminationFrontPort': RefInfo(object_type='dcim.frontport', field_name='termination', is_generic=True),
        'terminationInterface': RefInfo(object_type='dcim.interface', field_name='termination', is_generic=True),
        'terminationPowerFeed': RefInfo(object_type='dcim.powerfeed', field_name='termination', is_generic=True),
        'terminationPowerOutlet': RefInfo(object_type='dcim.poweroutlet', field_name='termination', is_generic=True),
        'terminationPowerPort': RefInfo(object_type='dcim.powerport', field_name='termination', is_generic=True),
        'terminationRearPort': RefInfo(object_type='dcim.rearport', field_name='termination', is_generic=True),
    },
    'dcim.consoleport': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.consoleserverport': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.device': {
        'cluster': RefInfo(object_type='virtualization.cluster', field_name='cluster'),
        'deviceType': RefInfo(object_type='dcim.devicetype', field_name='device_type'),
        'location': RefInfo(object_type='dcim.location', field_name='location'),
        'oobIp': RefInfo(object_type='ipam.ipaddress', field_name='oob_ip'),
        'platform': RefInfo(object_type='dcim.platform', field_name='platform'),
        'primaryIp4': RefInfo(object_type='ipam.ipaddress', field_name='primary_ip4'),
        'primaryIp6': RefInfo(object_type='ipam.ipaddress', field_name='primary_ip6'),
        'rack': RefInfo(object_type='dcim.rack', field_name='rack'),
        'role': RefInfo(object_type='dcim.devicerole', field_name='role'),
        'site': RefInfo(object_type='dcim.site', field_name='site'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'virtualChassis': RefInfo(object_type='dcim.virtualchassis', field_name='virtual_chassis'),
    },
    'dcim.devicebay': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'installedDevice': RefInfo(object_type='dcim.device', field_name='installed_device'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.devicerole': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.devicetype': {
        'defaultPlatform': RefInfo(object_type='dcim.platform', field_name='default_platform'),
        'manufacturer': RefInfo(object_type='dcim.manufacturer', field_name='manufacturer'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.frontport': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'rearPort': RefInfo(object_type='dcim.rearport', field_name='rear_port'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.interface': {
        'bridge': RefInfo(object_type='dcim.interface', field_name='bridge'),
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'lag': RefInfo(object_type='dcim.interface', field_name='lag'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'parent': RefInfo(object_type='dcim.interface', field_name='parent'),
        'primaryMacAddress': RefInfo(object_type='dcim.macaddress', field_name='primary_mac_address'),
        'qinqSvlan': RefInfo(object_type='ipam.vlan', field_name='qinq_svlan'),
        'taggedVlans': RefInfo(object_type='ipam.vlan', field_name='tagged_vlans', is_many=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'untaggedVlan': RefInfo(object_type='ipam.vlan', field_name='untagged_vlan'),
        'vdcs': RefInfo(object_type='dcim.virtualdevicecontext', field_name='vdcs', is_many=True),
        'vlanTranslationPolicy': RefInfo(object_type='ipam.vlantranslationpolicy', field_name='vlan_translation_policy'),
        'vrf': RefInfo(object_type='ipam.vrf', field_name='vrf'),
        'wirelessLans': RefInfo(object_type='wireless.wirelesslan', field_name='wireless_lans', is_many=True),
    },
    'dcim.inventoryitem': {
        'componentConsolePort': RefInfo(object_type='dcim.consoleport', field_name='component', is_generic=True),
        'componentConsoleServerPort': RefInfo(object_type='dcim.consoleserverport', field_name='component', is_generic=True),
        'componentFrontPort': RefInfo(object_type='dcim.frontport', field_name='component', is_generic=True),
        'componentInterface': RefInfo(object_type='dcim.interface', field_name='component', is_generic=True),
        'componentPowerOutlet': RefInfo(object_type='dcim.poweroutlet', field_name='component', is_generic=True),
        'componentPowerPort': RefInfo(object_type='dcim.powerport', field_name='component', is_generic=True),
        'componentRearPort': RefInfo(object_type='dcim.rearport', field_name='component', is_generic=True),
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'manufacturer': RefInfo(object_type='dcim.manufacturer', field_name='manufacturer'),
        'parent': RefInfo(object_type='dcim.inventoryitem', field_name='parent'),
        'role': RefInfo(object_type='dcim.inventoryitemrole', field_name='role'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.inventoryitemrole': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.location': {
        'parent': RefInfo(object_type='dcim.location', field_name='parent'),
        'site': RefInfo(object_type='dcim.site', field_name='site'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'dcim.macaddress': {
        'assignedObjectInterface': RefInfo(object_type='dcim.interface', field_name='assigned_object', is_generic=True),
        'assignedObjectVmInterface': RefInfo(object_type='virtualization.vminterface', field_name='assigned_object', is_generic=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.manufacturer': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.module': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'moduleBay': RefInfo(object_type='dcim.modulebay', field_name='module_bay'),
        'moduleType': RefInfo(object_type='dcim.moduletype', field_name='module_type'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.modulebay': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'installedModule': RefInfo(object_type='dcim.module', field_name='installed_module'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.moduletype': {
        'manufacturer': RefInfo(object_type='dcim.manufacturer', field_name='manufacturer'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.platform': {
        'manufacturer': RefInfo(object_type='dcim.manufacturer', field_name='manufacturer'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.powerfeed': {
        'powerPanel': RefInfo(object_type='dcim.powerpanel', field_name='power_panel'),
        'rack': RefInfo(object_type='dcim.rack', field_name='rack'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'dcim.poweroutlet': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'powerPort': RefInfo(object_type='dcim.powerport', field_name='power_port'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.powerpanel': {
        'location': RefInfo(object_type='dcim.location', field_name='location'),
        'site': RefInfo(object_type='dcim.site', field_name='site'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.powerport': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.rack': {
        'location': RefInfo(object_type='dcim.location', field_name='location'),
        'rackType': RefInfo(object_type='dcim.racktype', field_name='rack_type'),
        'role': RefInfo(object_type='dcim.rackrole', field_name='role'),
        'site': RefInfo(object_type='dcim.site', field_name='site'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'dcim.rackreservation': {
        'rack': RefInfo(object_type='dcim.rack', field_name='rack'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'dcim.rackrole': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.racktype': {
        'manufacturer': RefInfo(object_type='dcim.manufacturer', field_name='manufacturer'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.rearport': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'module': RefInfo(object_type='dcim.module', field_name='module'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.region': {
        'parent': RefInfo(object_type='dcim.region', field_name='parent'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.site': {
        'asns': RefInfo(object_type='ipam.asn', field_name='asns', is_many=True),
        'group': RefInfo(object_type='dcim.sitegroup', field_name='group'),
        'region': RefInfo(object_type='dcim.region', field_name='region'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'dcim.sitegroup': {
        'parent': RefInfo(object_type='dcim.sitegroup', field_name='parent'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.virtualchassis': {
        'master': RefInfo(object_type='dcim.device', field_name='master'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'dcim.virtualdevicecontext': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'primaryIp4': RefInfo(object_type='ipam.ipaddress', field_name='primary_ip4'),
        'primaryIp6': RefInfo(object_type='ipam.ipaddress', field_name='primary_ip6'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'ipam.aggregate': {
        'rir': RefInfo(object_type='ipam.rir', field_name='rir'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'ipam.asn': {
        'rir': RefInfo(object_type='ipam.rir', field_name='rir'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'ipam.asnrange': {
        'rir': RefInfo(object_type='ipam.rir', field_name='rir'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'ipam.fhrpgroup': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'ipam.fhrpgroupassignment': {
        'group': RefInfo(object_type='ipam.fhrpgroup', field_name='group'),
        'interfaceAsn': RefInfo(object_type='ipam.asn', field_name='interface', is_generic=True),
        'interfaceAsnRange': RefInfo(object_type='ipam.asnrange', field_name='interface', is_generic=True),
        'interfaceAggregate': RefInfo(object_type='ipam.aggregate', field_name='interface', is_generic=True),
        'interfaceCable': RefInfo(object_type='dcim.cable', field_name='interface', is_generic=True),
        'interfaceCablePath': RefInfo(object_type='dcim.cablepath', field_name='interface', is_generic=True),
        'interfaceCableTermination': RefInfo(object_type='dcim.cabletermination', field_name='interface', is_generic=True),
        'interfaceCircuit': RefInfo(object_type='circuits.circuit', field_name='interface', is_generic=True),
        'interfaceCircuitGroup': RefInfo(object_type='circuits.circuitgroup', field_name='interface', is_generic=True),
        'interfaceCircuitGroupAssignment': RefInfo(object_type='circuits.circuitgroupassignment', field_name='interface', is_generic=True),
        'interfaceCircuitTermination': RefInfo(object_type='circuits.circuittermination', field_name='interface', is_generic=True),
        'interfaceCircuitType': RefInfo(object_type='circuits.circuittype', field_name='interface', is_generic=True),
        'interfaceCluster': RefInfo(object_type='virtualization.cluster', field_name='interface', is_generic=True),
        'interfaceClusterGroup': RefInfo(object_type='virtualization.clustergroup', field_name='interface', is_generic=True),
        'interfaceClusterType': RefInfo(object_type='virtualization.clustertype', field_name='interface', is_generic=True),
        'interfaceConsolePort': RefInfo(object_type='dcim.consoleport', field_name='interface', is_generic=True),
        'interfaceConsoleServerPort': RefInfo(object_type='dcim.consoleserverport', field_name='interface', is_generic=True),
        'interfaceContact': RefInfo(object_type='tenancy.contact', field_name='interface', is_generic=True),
        'interfaceContactAssignment': RefInfo(object_type='tenancy.contactassignment', field_name='interface', is_generic=True),
        'interfaceContactGroup': RefInfo(object_type='tenancy.contactgroup', field_name='interface', is_generic=True),
        'interfaceContactRole': RefInfo(object_type='tenancy.contactrole', field_name='interface', is_generic=True),
        'interfaceDevice': RefInfo(object_type='dcim.device', field_name='interface', is_generic=True),
        'interfaceDeviceBay': RefInfo(object_type='dcim.devicebay', field_name='interface', is_generic=True),
        'interfaceDeviceRole': RefInfo(object_type='dcim.devicerole', field_name='interface', is_generic=True),
        'interfaceDeviceType': RefInfo(object_type='dcim.devicetype', field_name='interface', is_generic=True),
        'interfaceFhrpGroup': RefInfo(object_type='ipam.fhrpgroup', field_name='interface', is_generic=True),
        'interfaceFhrpGroupAssignment': RefInfo(object_type='ipam.fhrpgroupassignment', field_name='interface', is_generic=True),
        'interfaceFrontPort': RefInfo(object_type='dcim.frontport', field_name='interface', is_generic=True),
        'interfaceIkePolicy': RefInfo(object_type='vpn.ikepolicy', field_name='interface', is_generic=True),
        'interfaceIkeProposal': RefInfo(object_type='vpn.ikeproposal', field_name='interface', is_generic=True),
        'interfaceIpAddress': RefInfo(object_type='ipam.ipaddress', field_name='interface', is_generic=True),
        'interfaceIpRange': RefInfo(object_type='ipam.iprange', field_name='interface', is_generic=True),
        'interfaceIpSecPolicy': RefInfo(object_type='vpn.ipsecpolicy', field_name='interface', is_generic=True),
        'interfaceIpSecProfile': RefInfo(object_type='vpn.ipsecprofile', field_name='interface', is_generic=True),
        'interfaceIpSecProposal': RefInfo(object_type='vpn.ipsecproposal', field_name='interface', is_generic=True),
        'interfaceInterface': RefInfo(object_type='dcim.interface', field_name='interface', is_generic=True),
        'interfaceInventoryItem': RefInfo(object_type='dcim.inventoryitem', field_name='interface', is_generic=True),
        'interfaceInventoryItemRole': RefInfo(object_type='dcim.inventoryitemrole', field_name='interface', is_generic=True),
        'interfaceL2Vpn': RefInfo(object_type='vpn.l2vpn', field_name='interface', is_generic=True),
        'interfaceL2VpnTermination': RefInfo(object_type='vpn.l2vpntermination', field_name='interface', is_generic=True),
        'interfaceLocation': RefInfo(object_type='dcim.location', field_name='interface', is_generic=True),
        'interfaceMacAddress': RefInfo(object_type='dcim.macaddress', field_name='interface', is_generic=True),
        'interfaceManufacturer': RefInfo(object_type='dcim.manufacturer', field_name='interface', is_generic=True),
        'interfaceModule': RefInfo(object_type='dcim.module', field_name='interface', is_generic=True),
        'interfaceModuleBay': RefInfo(object_type='dcim.modulebay', field_name='interface', is_generic=True),
        'interfaceModuleType': RefInfo(object_type='dcim.moduletype', field_name='interface', is_generic=True),
        'interfacePlatform': RefInfo(object_type='dcim.platform', field_name='interface', is_generic=True),
        'interfacePowerFeed': RefInfo(object_type='dcim.powerfeed', field_name='interface', is_generic=True),
        'interfacePowerOutlet': RefInfo(object_type='dcim.poweroutlet', field_name='interface', is_generic=True),
        'interfacePowerPanel': RefInfo(object_type='dcim.powerpanel', field_name='interface', is_generic=True),
        'interfacePowerPort': RefInfo(object_type='dcim.powerport', field_name='interface', is_generic=True),
        'interfacePrefix': RefInfo(object_type='ipam.prefix', field_name='interface', is_generic=True),
        'interfaceProvider': RefInfo(object_type='circuits.provider', field_name='interface', is_generic=True),
        'interfaceProviderAccount': RefInfo(object_type='circuits.provideraccount', field_name='interface', is_generic=True),
        'interfaceProviderNetwork': RefInfo(object_type='circuits.providernetwork', field_name='interface', is_generic=True),
        'interfaceRir': RefInfo(object_type='ipam.rir', field_name='interface', is_generic=True),
        'interfaceRack': RefInfo(object_type='dcim.rack', field_name='interface', is_generic=True),
        'interfaceRackReservation': RefInfo(object_type='dcim.rackreservation', field_name='interface', is_generic=True),
        'interfaceRackRole': RefInfo(object_type='dcim.rackrole', field_name='interface', is_generic=True),
        'interfaceRackType': RefInfo(object_type='dcim.racktype', field_name='interface', is_generic=True),
        'interfaceRearPort': RefInfo(object_type='dcim.rearport', field_name='interface', is_generic=True),
        'interfaceRegion': RefInfo(object_type='dcim.region', field_name='interface', is_generic=True),
        'interfaceRole': RefInfo(object_type='ipam.role', field_name='interface', is_generic=True),
        'interfaceRouteTarget': RefInfo(object_type='ipam.routetarget', field_name='interface', is_generic=True),
        'interfaceService': RefInfo(object_type='ipam.service', field_name='interface', is_generic=True),
        'interfaceSite': RefInfo(object_type='dcim.site', field_name='interface', is_generic=True),
        'interfaceSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='interface', is_generic=True),
        'interfaceTag': RefInfo(object_type='extras.tag', field_name='interface', is_generic=True),
        'interfaceTenant': RefInfo(object_type='tenancy.tenant', field_name='interface', is_generic=True),
        'interfaceTenantGroup': RefInfo(object_type='tenancy.tenantgroup', field_name='interface', is_generic=True),
        'interfaceTunnel': RefInfo(object_type='vpn.tunnel', field_name='interface', is_generic=True),
        'interfaceTunnelGroup': RefInfo(object_type='vpn.tunnelgroup', field_name='interface', is_generic=True),
        'interfaceTunnelTermination': RefInfo(object_type='vpn.tunneltermination', field_name='interface', is_generic=True),
        'interfaceVlan': RefInfo(object_type='ipam.vlan', field_name='interface', is_generic=True),
        'interfaceVlanGroup': RefInfo(object_type='ipam.vlangroup', field_name='interface', is_generic=True),
        'interfaceVlanTranslationPolicy': RefInfo(object_type='ipam.vlantranslationpolicy', field_name='interface', is_generic=True),
        'interfaceVlanTranslationRule': RefInfo(object_type='ipam.vlantranslationrule', field_name='interface', is_generic=True),
        'interfaceVmInterface': RefInfo(object_type='virtualization.vminterface', field_name='interface', is_generic=True),
        'interfaceVrf': RefInfo(object_type='ipam.vrf', field_name='interface', is_generic=True),
        'interfaceVirtualChassis': RefInfo(object_type='dcim.virtualchassis', field_name='interface', is_generic=True),
        'interfaceVirtualCircuit': RefInfo(object_type='circuits.virtualcircuit', field_name='interface', is_generic=True),
        'interfaceVirtualCircuitTermination': RefInfo(object_type='circuits.virtualcircuittermination', field_name='interface', is_generic=True),
        'interfaceVirtualCircuitType': RefInfo(object_type='circuits.virtualcircuittype', field_name='interface', is_generic=True),
        'interfaceVirtualDeviceContext': RefInfo(object_type='dcim.virtualdevicecontext', field_name='interface', is_generic=True),
        'interfaceVirtualDisk': RefInfo(object_type='virtualization.virtualdisk', field_name='interface', is_generic=True),
        'interfaceVirtualMachine': RefInfo(object_type='virtualization.virtualmachine', field_name='interface', is_generic=True),
        'interfaceWirelessLan': RefInfo(object_type='wireless.wirelesslan', field_name='interface', is_generic=True),
        'interfaceWirelessLanGroup': RefInfo(object_type='wireless.wirelesslangroup', field_name='interface', is_generic=True),
        'interfaceWirelessLink': RefInfo(object_type='wireless.wirelesslink', field_name='interface', is_generic=True),
    },
    'ipam.ipaddress': {
        'assignedObjectFhrpGroup': RefInfo(object_type='ipam.fhrpgroup', field_name='assigned_object', is_generic=True),
        'assignedObjectInterface': RefInfo(object_type='dcim.interface', field_name='assigned_object', is_generic=True),
        'assignedObjectVmInterface': RefInfo(object_type='virtualization.vminterface', field_name='assigned_object', is_generic=True),
        'natInside': RefInfo(object_type='ipam.ipaddress', field_name='nat_inside'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'vrf': RefInfo(object_type='ipam.vrf', field_name='vrf'),
    },
    'ipam.iprange': {
        'role': RefInfo(object_type='ipam.role', field_name='role'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'vrf': RefInfo(object_type='ipam.vrf', field_name='vrf'),
    },
    'ipam.prefix': {
        'role': RefInfo(object_type='ipam.role', field_name='role'),
        'scopeLocation': RefInfo(object_type='dcim.location', field_name='scope', is_generic=True),
        'scopeRegion': RefInfo(object_type='dcim.region', field_name='scope', is_generic=True),
        'scopeSite': RefInfo(object_type='dcim.site', field_name='scope', is_generic=True),
        'scopeSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='scope', is_generic=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'vlan': RefInfo(object_type='ipam.vlan', field_name='vlan'),
        'vrf': RefInfo(object_type='ipam.vrf', field_name='vrf'),
    },
    'ipam.rir': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'ipam.role': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'ipam.routetarget': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'ipam.service': {
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'ipaddresses': RefInfo(object_type='ipam.ipaddress', field_name='ipaddresses', is_many=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'virtualMachine': RefInfo(object_type='virtualization.virtualmachine', field_name='virtual_machine'),
    },
    'ipam.vlan': {
        'group': RefInfo(object_type='ipam.vlangroup', field_name='group'),
        'qinqSvlan': RefInfo(object_type='ipam.vlan', field_name='qinq_svlan'),
        'role': RefInfo(object_type='ipam.role', field_name='role'),
        'site': RefInfo(object_type='dcim.site', field_name='site'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'ipam.vlangroup': {
        'scopeCluster': RefInfo(object_type='virtualization.cluster', field_name='scope', is_generic=True),
        'scopeClusterGroup': RefInfo(object_type='virtualization.clustergroup', field_name='scope', is_generic=True),
        'scopeLocation': RefInfo(object_type='dcim.location', field_name='scope', is_generic=True),
        'scopeRack': RefInfo(object_type='dcim.rack', field_name='scope', is_generic=True),
        'scopeRegion': RefInfo(object_type='dcim.region', field_name='scope', is_generic=True),
        'scopeSite': RefInfo(object_type='dcim.site', field_name='scope', is_generic=True),
        'scopeSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='scope', is_generic=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'ipam.vlantranslationrule': {
        'policy': RefInfo(object_type='ipam.vlantranslationpolicy', field_name='policy'),
    },
    'ipam.vrf': {
        'exportTargets': RefInfo(object_type='ipam.routetarget', field_name='export_targets', is_many=True),
        'importTargets': RefInfo(object_type='ipam.routetarget', field_name='import_targets', is_many=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'tenancy.contact': {
        'group': RefInfo(object_type='tenancy.contactgroup', field_name='group'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'tenancy.contactassignment': {
        'contact': RefInfo(object_type='tenancy.contact', field_name='contact'),
        'objectAsn': RefInfo(object_type='ipam.asn', field_name='object', is_generic=True),
        'objectAsnRange': RefInfo(object_type='ipam.asnrange', field_name='object', is_generic=True),
        'objectAggregate': RefInfo(object_type='ipam.aggregate', field_name='object', is_generic=True),
        'objectCable': RefInfo(object_type='dcim.cable', field_name='object', is_generic=True),
        'objectCablePath': RefInfo(object_type='dcim.cablepath', field_name='object', is_generic=True),
        'objectCableTermination': RefInfo(object_type='dcim.cabletermination', field_name='object', is_generic=True),
        'objectCircuit': RefInfo(object_type='circuits.circuit', field_name='object', is_generic=True),
        'objectCircuitGroup': RefInfo(object_type='circuits.circuitgroup', field_name='object', is_generic=True),
        'objectCircuitGroupAssignment': RefInfo(object_type='circuits.circuitgroupassignment', field_name='object', is_generic=True),
        'objectCircuitTermination': RefInfo(object_type='circuits.circuittermination', field_name='object', is_generic=True),
        'objectCircuitType': RefInfo(object_type='circuits.circuittype', field_name='object', is_generic=True),
        'objectCluster': RefInfo(object_type='virtualization.cluster', field_name='object', is_generic=True),
        'objectClusterGroup': RefInfo(object_type='virtualization.clustergroup', field_name='object', is_generic=True),
        'objectClusterType': RefInfo(object_type='virtualization.clustertype', field_name='object', is_generic=True),
        'objectConsolePort': RefInfo(object_type='dcim.consoleport', field_name='object', is_generic=True),
        'objectConsoleServerPort': RefInfo(object_type='dcim.consoleserverport', field_name='object', is_generic=True),
        'objectContact': RefInfo(object_type='tenancy.contact', field_name='object', is_generic=True),
        'objectContactAssignment': RefInfo(object_type='tenancy.contactassignment', field_name='object', is_generic=True),
        'objectContactGroup': RefInfo(object_type='tenancy.contactgroup', field_name='object', is_generic=True),
        'objectContactRole': RefInfo(object_type='tenancy.contactrole', field_name='object', is_generic=True),
        'objectDevice': RefInfo(object_type='dcim.device', field_name='object', is_generic=True),
        'objectDeviceBay': RefInfo(object_type='dcim.devicebay', field_name='object', is_generic=True),
        'objectDeviceRole': RefInfo(object_type='dcim.devicerole', field_name='object', is_generic=True),
        'objectDeviceType': RefInfo(object_type='dcim.devicetype', field_name='object', is_generic=True),
        'objectFhrpGroup': RefInfo(object_type='ipam.fhrpgroup', field_name='object', is_generic=True),
        'objectFhrpGroupAssignment': RefInfo(object_type='ipam.fhrpgroupassignment', field_name='object', is_generic=True),
        'objectFrontPort': RefInfo(object_type='dcim.frontport', field_name='object', is_generic=True),
        'objectIkePolicy': RefInfo(object_type='vpn.ikepolicy', field_name='object', is_generic=True),
        'objectIkeProposal': RefInfo(object_type='vpn.ikeproposal', field_name='object', is_generic=True),
        'objectIpAddress': RefInfo(object_type='ipam.ipaddress', field_name='object', is_generic=True),
        'objectIpRange': RefInfo(object_type='ipam.iprange', field_name='object', is_generic=True),
        'objectIpSecPolicy': RefInfo(object_type='vpn.ipsecpolicy', field_name='object', is_generic=True),
        'objectIpSecProfile': RefInfo(object_type='vpn.ipsecprofile', field_name='object', is_generic=True),
        'objectIpSecProposal': RefInfo(object_type='vpn.ipsecproposal', field_name='object', is_generic=True),
        'objectInterface': RefInfo(object_type='dcim.interface', field_name='object', is_generic=True),
        'objectInventoryItem': RefInfo(object_type='dcim.inventoryitem', field_name='object', is_generic=True),
        'objectInventoryItemRole': RefInfo(object_type='dcim.inventoryitemrole', field_name='object', is_generic=True),
        'objectL2Vpn': RefInfo(object_type='vpn.l2vpn', field_name='object', is_generic=True),
        'objectL2VpnTermination': RefInfo(object_type='vpn.l2vpntermination', field_name='object', is_generic=True),
        'objectLocation': RefInfo(object_type='dcim.location', field_name='object', is_generic=True),
        'objectMacAddress': RefInfo(object_type='dcim.macaddress', field_name='object', is_generic=True),
        'objectManufacturer': RefInfo(object_type='dcim.manufacturer', field_name='object', is_generic=True),
        'objectModule': RefInfo(object_type='dcim.module', field_name='object', is_generic=True),
        'objectModuleBay': RefInfo(object_type='dcim.modulebay', field_name='object', is_generic=True),
        'objectModuleType': RefInfo(object_type='dcim.moduletype', field_name='object', is_generic=True),
        'objectPlatform': RefInfo(object_type='dcim.platform', field_name='object', is_generic=True),
        'objectPowerFeed': RefInfo(object_type='dcim.powerfeed', field_name='object', is_generic=True),
        'objectPowerOutlet': RefInfo(object_type='dcim.poweroutlet', field_name='object', is_generic=True),
        'objectPowerPanel': RefInfo(object_type='dcim.powerpanel', field_name='object', is_generic=True),
        'objectPowerPort': RefInfo(object_type='dcim.powerport', field_name='object', is_generic=True),
        'objectPrefix': RefInfo(object_type='ipam.prefix', field_name='object', is_generic=True),
        'objectProvider': RefInfo(object_type='circuits.provider', field_name='object', is_generic=True),
        'objectProviderAccount': RefInfo(object_type='circuits.provideraccount', field_name='object', is_generic=True),
        'objectProviderNetwork': RefInfo(object_type='circuits.providernetwork', field_name='object', is_generic=True),
        'objectRir': RefInfo(object_type='ipam.rir', field_name='object', is_generic=True),
        'objectRack': RefInfo(object_type='dcim.rack', field_name='object', is_generic=True),
        'objectRackReservation': RefInfo(object_type='dcim.rackreservation', field_name='object', is_generic=True),
        'objectRackRole': RefInfo(object_type='dcim.rackrole', field_name='object', is_generic=True),
        'objectRackType': RefInfo(object_type='dcim.racktype', field_name='object', is_generic=True),
        'objectRearPort': RefInfo(object_type='dcim.rearport', field_name='object', is_generic=True),
        'objectRegion': RefInfo(object_type='dcim.region', field_name='object', is_generic=True),
        'objectRole': RefInfo(object_type='ipam.role', field_name='object', is_generic=True),
        'objectRouteTarget': RefInfo(object_type='ipam.routetarget', field_name='object', is_generic=True),
        'objectService': RefInfo(object_type='ipam.service', field_name='object', is_generic=True),
        'objectSite': RefInfo(object_type='dcim.site', field_name='object', is_generic=True),
        'objectSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='object', is_generic=True),
        'objectTag': RefInfo(object_type='extras.tag', field_name='object', is_generic=True),
        'objectTenant': RefInfo(object_type='tenancy.tenant', field_name='object', is_generic=True),
        'objectTenantGroup': RefInfo(object_type='tenancy.tenantgroup', field_name='object', is_generic=True),
        'objectTunnel': RefInfo(object_type='vpn.tunnel', field_name='object', is_generic=True),
        'objectTunnelGroup': RefInfo(object_type='vpn.tunnelgroup', field_name='object', is_generic=True),
        'objectTunnelTermination': RefInfo(object_type='vpn.tunneltermination', field_name='object', is_generic=True),
        'objectVlan': RefInfo(object_type='ipam.vlan', field_name='object', is_generic=True),
        'objectVlanGroup': RefInfo(object_type='ipam.vlangroup', field_name='object', is_generic=True),
        'objectVlanTranslationPolicy': RefInfo(object_type='ipam.vlantranslationpolicy', field_name='object', is_generic=True),
        'objectVlanTranslationRule': RefInfo(object_type='ipam.vlantranslationrule', field_name='object', is_generic=True),
        'objectVmInterface': RefInfo(object_type='virtualization.vminterface', field_name='object', is_generic=True),
        'objectVrf': RefInfo(object_type='ipam.vrf', field_name='object', is_generic=True),
        'objectVirtualChassis': RefInfo(object_type='dcim.virtualchassis', field_name='object', is_generic=True),
        'objectVirtualCircuit': RefInfo(object_type='circuits.virtualcircuit', field_name='object', is_generic=True),
        'objectVirtualCircuitTermination': RefInfo(object_type='circuits.virtualcircuittermination', field_name='object', is_generic=True),
        'objectVirtualCircuitType': RefInfo(object_type='circuits.virtualcircuittype', field_name='object', is_generic=True),
        'objectVirtualDeviceContext': RefInfo(object_type='dcim.virtualdevicecontext', field_name='object', is_generic=True),
        'objectVirtualDisk': RefInfo(object_type='virtualization.virtualdisk', field_name='object', is_generic=True),
        'objectVirtualMachine': RefInfo(object_type='virtualization.virtualmachine', field_name='object', is_generic=True),
        'objectWirelessLan': RefInfo(object_type='wireless.wirelesslan', field_name='object', is_generic=True),
        'objectWirelessLanGroup': RefInfo(object_type='wireless.wirelesslangroup', field_name='object', is_generic=True),
        'objectWirelessLink': RefInfo(object_type='wireless.wirelesslink', field_name='object', is_generic=True),
        'role': RefInfo(object_type='tenancy.contactrole', field_name='role'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'tenancy.contactgroup': {
        'parent': RefInfo(object_type='tenancy.contactgroup', field_name='parent'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'tenancy.contactrole': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'tenancy.tenant': {
        'group': RefInfo(object_type='tenancy.tenantgroup', field_name='group'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'tenancy.tenantgroup': {
        'parent': RefInfo(object_type='tenancy.tenantgroup', field_name='parent'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'virtualization.cluster': {
        'group': RefInfo(object_type='virtualization.clustergroup', field_name='group'),
        'scopeLocation': RefInfo(object_type='dcim.location', field_name='scope', is_generic=True),
        'scopeRegion': RefInfo(object_type='dcim.region', field_name='scope', is_generic=True),
        'scopeSite': RefInfo(object_type='dcim.site', field_name='scope', is_generic=True),
        'scopeSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='scope', is_generic=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'type': RefInfo(object_type='virtualization.clustertype', field_name='type'),
    },
    'virtualization.clustergroup': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'virtualization.clustertype': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'virtualization.virtualdisk': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'virtualMachine': RefInfo(object_type='virtualization.virtualmachine', field_name='virtual_machine'),
    },
    'virtualization.virtualmachine': {
        'cluster': RefInfo(object_type='virtualization.cluster', field_name='cluster'),
        'device': RefInfo(object_type='dcim.device', field_name='device'),
        'platform': RefInfo(object_type='dcim.platform', field_name='platform'),
        'primaryIp4': RefInfo(object_type='ipam.ipaddress', field_name='primary_ip4'),
        'primaryIp6': RefInfo(object_type='ipam.ipaddress', field_name='primary_ip6'),
        'role': RefInfo(object_type='dcim.devicerole', field_name='role'),
        'site': RefInfo(object_type='dcim.site', field_name='site'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'virtualization.vminterface': {
        'bridge': RefInfo(object_type='virtualization.vminterface', field_name='bridge'),
        'parent': RefInfo(object_type='virtualization.vminterface', field_name='parent'),
        'primaryMacAddress': RefInfo(object_type='dcim.macaddress', field_name='primary_mac_address'),
        'qinqSvlan': RefInfo(object_type='ipam.vlan', field_name='qinq_svlan'),
        'taggedVlans': RefInfo(object_type='ipam.vlan', field_name='tagged_vlans', is_many=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'untaggedVlan': RefInfo(object_type='ipam.vlan', field_name='untagged_vlan'),
        'virtualMachine': RefInfo(object_type='virtualization.virtualmachine', field_name='virtual_machine'),
        'vlanTranslationPolicy': RefInfo(object_type='ipam.vlantranslationpolicy', field_name='vlan_translation_policy'),
        'vrf': RefInfo(object_type='ipam.vrf', field_name='vrf'),
    },
    'vpn.ikepolicy': {
        'proposals': RefInfo(object_type='vpn.ikeproposal', field_name='proposals', is_many=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'vpn.ikeproposal': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'vpn.ipsecpolicy': {
        'proposals': RefInfo(object_type='vpn.ipsecproposal', field_name='proposals', is_many=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'vpn.ipsecprofile': {
        'ikePolicy': RefInfo(object_type='vpn.ikepolicy', field_name='ike_policy'),
        'ipsecPolicy': RefInfo(object_type='vpn.ipsecpolicy', field_name='ipsec_policy'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'vpn.ipsecproposal': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'vpn.l2vpn': {
        'exportTargets': RefInfo(object_type='ipam.routetarget', field_name='export_targets', is_many=True),
        'importTargets': RefInfo(object_type='ipam.routetarget', field_name='import_targets', is_many=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'vpn.l2vpntermination': {
        'assignedObjectInterface': RefInfo(object_type='dcim.interface', field_name='assigned_object', is_generic=True),
        'assignedObjectVlan': RefInfo(object_type='ipam.vlan', field_name='assigned_object', is_generic=True),
        'assignedObjectVmInterface': RefInfo(object_type='virtualization.vminterface', field_name='assigned_object', is_generic=True),
        'l2Vpn': RefInfo(object_type='vpn.l2vpn', field_name='l2vpn'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'vpn.tunnel': {
        'group': RefInfo(object_type='vpn.tunnelgroup', field_name='group'),
        'ipsecProfile': RefInfo(object_type='vpn.ipsecprofile', field_name='ipsec_profile'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
    'vpn.tunnelgroup': {
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'vpn.tunneltermination': {
        'outsideIp': RefInfo(object_type='ipam.ipaddress', field_name='outside_ip'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'terminationAsn': RefInfo(object_type='ipam.asn', field_name='termination', is_generic=True),
        'terminationAsnRange': RefInfo(object_type='ipam.asnrange', field_name='termination', is_generic=True),
        'terminationAggregate': RefInfo(object_type='ipam.aggregate', field_name='termination', is_generic=True),
        'terminationCable': RefInfo(object_type='dcim.cable', field_name='termination', is_generic=True),
        'terminationCablePath': RefInfo(object_type='dcim.cablepath', field_name='termination', is_generic=True),
        'terminationCableTermination': RefInfo(object_type='dcim.cabletermination', field_name='termination', is_generic=True),
        'terminationCircuit': RefInfo(object_type='circuits.circuit', field_name='termination', is_generic=True),
        'terminationCircuitGroup': RefInfo(object_type='circuits.circuitgroup', field_name='termination', is_generic=True),
        'terminationCircuitGroupAssignment': RefInfo(object_type='circuits.circuitgroupassignment', field_name='termination', is_generic=True),
        'terminationCircuitTermination': RefInfo(object_type='circuits.circuittermination', field_name='termination', is_generic=True),
        'terminationCircuitType': RefInfo(object_type='circuits.circuittype', field_name='termination', is_generic=True),
        'terminationCluster': RefInfo(object_type='virtualization.cluster', field_name='termination', is_generic=True),
        'terminationClusterGroup': RefInfo(object_type='virtualization.clustergroup', field_name='termination', is_generic=True),
        'terminationClusterType': RefInfo(object_type='virtualization.clustertype', field_name='termination', is_generic=True),
        'terminationConsolePort': RefInfo(object_type='dcim.consoleport', field_name='termination', is_generic=True),
        'terminationConsoleServerPort': RefInfo(object_type='dcim.consoleserverport', field_name='termination', is_generic=True),
        'terminationContact': RefInfo(object_type='tenancy.contact', field_name='termination', is_generic=True),
        'terminationContactAssignment': RefInfo(object_type='tenancy.contactassignment', field_name='termination', is_generic=True),
        'terminationContactGroup': RefInfo(object_type='tenancy.contactgroup', field_name='termination', is_generic=True),
        'terminationContactRole': RefInfo(object_type='tenancy.contactrole', field_name='termination', is_generic=True),
        'terminationDevice': RefInfo(object_type='dcim.device', field_name='termination', is_generic=True),
        'terminationDeviceBay': RefInfo(object_type='dcim.devicebay', field_name='termination', is_generic=True),
        'terminationDeviceRole': RefInfo(object_type='dcim.devicerole', field_name='termination', is_generic=True),
        'terminationDeviceType': RefInfo(object_type='dcim.devicetype', field_name='termination', is_generic=True),
        'terminationFhrpGroup': RefInfo(object_type='ipam.fhrpgroup', field_name='termination', is_generic=True),
        'terminationFhrpGroupAssignment': RefInfo(object_type='ipam.fhrpgroupassignment', field_name='termination', is_generic=True),
        'terminationFrontPort': RefInfo(object_type='dcim.frontport', field_name='termination', is_generic=True),
        'terminationIkePolicy': RefInfo(object_type='vpn.ikepolicy', field_name='termination', is_generic=True),
        'terminationIkeProposal': RefInfo(object_type='vpn.ikeproposal', field_name='termination', is_generic=True),
        'terminationIpAddress': RefInfo(object_type='ipam.ipaddress', field_name='termination', is_generic=True),
        'terminationIpRange': RefInfo(object_type='ipam.iprange', field_name='termination', is_generic=True),
        'terminationIpSecPolicy': RefInfo(object_type='vpn.ipsecpolicy', field_name='termination', is_generic=True),
        'terminationIpSecProfile': RefInfo(object_type='vpn.ipsecprofile', field_name='termination', is_generic=True),
        'terminationIpSecProposal': RefInfo(object_type='vpn.ipsecproposal', field_name='termination', is_generic=True),
        'terminationInterface': RefInfo(object_type='dcim.interface', field_name='termination', is_generic=True),
        'terminationInventoryItem': RefInfo(object_type='dcim.inventoryitem', field_name='termination', is_generic=True),
        'terminationInventoryItemRole': RefInfo(object_type='dcim.inventoryitemrole', field_name='termination', is_generic=True),
        'terminationL2Vpn': RefInfo(object_type='vpn.l2vpn', field_name='termination', is_generic=True),
        'terminationL2VpnTermination': RefInfo(object_type='vpn.l2vpntermination', field_name='termination', is_generic=True),
        'terminationLocation': RefInfo(object_type='dcim.location', field_name='termination', is_generic=True),
        'terminationMacAddress': RefInfo(object_type='dcim.macaddress', field_name='termination', is_generic=True),
        'terminationManufacturer': RefInfo(object_type='dcim.manufacturer', field_name='termination', is_generic=True),
        'terminationModule': RefInfo(object_type='dcim.module', field_name='termination', is_generic=True),
        'terminationModuleBay': RefInfo(object_type='dcim.modulebay', field_name='termination', is_generic=True),
        'terminationModuleType': RefInfo(object_type='dcim.moduletype', field_name='termination', is_generic=True),
        'terminationPlatform': RefInfo(object_type='dcim.platform', field_name='termination', is_generic=True),
        'terminationPowerFeed': RefInfo(object_type='dcim.powerfeed', field_name='termination', is_generic=True),
        'terminationPowerOutlet': RefInfo(object_type='dcim.poweroutlet', field_name='termination', is_generic=True),
        'terminationPowerPanel': RefInfo(object_type='dcim.powerpanel', field_name='termination', is_generic=True),
        'terminationPowerPort': RefInfo(object_type='dcim.powerport', field_name='termination', is_generic=True),
        'terminationPrefix': RefInfo(object_type='ipam.prefix', field_name='termination', is_generic=True),
        'terminationProvider': RefInfo(object_type='circuits.provider', field_name='termination', is_generic=True),
        'terminationProviderAccount': RefInfo(object_type='circuits.provideraccount', field_name='termination', is_generic=True),
        'terminationProviderNetwork': RefInfo(object_type='circuits.providernetwork', field_name='termination', is_generic=True),
        'terminationRir': RefInfo(object_type='ipam.rir', field_name='termination', is_generic=True),
        'terminationRack': RefInfo(object_type='dcim.rack', field_name='termination', is_generic=True),
        'terminationRackReservation': RefInfo(object_type='dcim.rackreservation', field_name='termination', is_generic=True),
        'terminationRackRole': RefInfo(object_type='dcim.rackrole', field_name='termination', is_generic=True),
        'terminationRackType': RefInfo(object_type='dcim.racktype', field_name='termination', is_generic=True),
        'terminationRearPort': RefInfo(object_type='dcim.rearport', field_name='termination', is_generic=True),
        'terminationRegion': RefInfo(object_type='dcim.region', field_name='termination', is_generic=True),
        'terminationRole': RefInfo(object_type='ipam.role', field_name='termination', is_generic=True),
        'terminationRouteTarget': RefInfo(object_type='ipam.routetarget', field_name='termination', is_generic=True),
        'terminationService': RefInfo(object_type='ipam.service', field_name='termination', is_generic=True),
        'terminationSite': RefInfo(object_type='dcim.site', field_name='termination', is_generic=True),
        'terminationSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='termination', is_generic=True),
        'terminationTag': RefInfo(object_type='extras.tag', field_name='termination', is_generic=True),
        'terminationTenant': RefInfo(object_type='tenancy.tenant', field_name='termination', is_generic=True),
        'terminationTenantGroup': RefInfo(object_type='tenancy.tenantgroup', field_name='termination', is_generic=True),
        'terminationTunnel': RefInfo(object_type='vpn.tunnel', field_name='termination', is_generic=True),
        'terminationTunnelGroup': RefInfo(object_type='vpn.tunnelgroup', field_name='termination', is_generic=True),
        'terminationTunnelTermination': RefInfo(object_type='vpn.tunneltermination', field_name='termination', is_generic=True),
        'terminationVlan': RefInfo(object_type='ipam.vlan', field_name='termination', is_generic=True),
        'terminationVlanGroup': RefInfo(object_type='ipam.vlangroup', field_name='termination', is_generic=True),
        'terminationVlanTranslationPolicy': RefInfo(object_type='ipam.vlantranslationpolicy', field_name='termination', is_generic=True),
        'terminationVlanTranslationRule': RefInfo(object_type='ipam.vlantranslationrule', field_name='termination', is_generic=True),
        'terminationVmInterface': RefInfo(object_type='virtualization.vminterface', field_name='termination', is_generic=True),
        'terminationVrf': RefInfo(object_type='ipam.vrf', field_name='termination', is_generic=True),
        'terminationVirtualChassis': RefInfo(object_type='dcim.virtualchassis', field_name='termination', is_generic=True),
        'terminationVirtualCircuit': RefInfo(object_type='circuits.virtualcircuit', field_name='termination', is_generic=True),
        'terminationVirtualCircuitTermination': RefInfo(object_type='circuits.virtualcircuittermination', field_name='termination', is_generic=True),
        'terminationVirtualCircuitType': RefInfo(object_type='circuits.virtualcircuittype', field_name='termination', is_generic=True),
        'terminationVirtualDeviceContext': RefInfo(object_type='dcim.virtualdevicecontext', field_name='termination', is_generic=True),
        'terminationVirtualDisk': RefInfo(object_type='virtualization.virtualdisk', field_name='termination', is_generic=True),
        'terminationVirtualMachine': RefInfo(object_type='virtualization.virtualmachine', field_name='termination', is_generic=True),
        'terminationWirelessLan': RefInfo(object_type='wireless.wirelesslan', field_name='termination', is_generic=True),
        'terminationWirelessLanGroup': RefInfo(object_type='wireless.wirelesslangroup', field_name='termination', is_generic=True),
        'terminationWirelessLink': RefInfo(object_type='wireless.wirelesslink', field_name='termination', is_generic=True),
        'tunnel': RefInfo(object_type='vpn.tunnel', field_name='tunnel'),
    },
    'wireless.wirelesslan': {
        'group': RefInfo(object_type='wireless.wirelesslangroup', field_name='group'),
        'scopeLocation': RefInfo(object_type='dcim.location', field_name='scope', is_generic=True),
        'scopeRegion': RefInfo(object_type='dcim.region', field_name='scope', is_generic=True),
        'scopeSite': RefInfo(object_type='dcim.site', field_name='scope', is_generic=True),
        'scopeSiteGroup': RefInfo(object_type='dcim.sitegroup', field_name='scope', is_generic=True),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
        'vlan': RefInfo(object_type='ipam.vlan', field_name='vlan'),
    },
    'wireless.wirelesslangroup': {
        'parent': RefInfo(object_type='wireless.wirelesslangroup', field_name='parent'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
    },
    'wireless.wirelesslink': {
        'interfaceA': RefInfo(object_type='dcim.interface', field_name='interface_a'),
        'interfaceB': RefInfo(object_type='dcim.interface', field_name='interface_b'),
        'tags': RefInfo(object_type='extras.tag', field_name='tags', is_many=True),
        'tenant': RefInfo(object_type='tenancy.tenant', field_name='tenant'),
    },
}

def get_json_ref_info(object_type: str|Type[models.Model], json_field_name: str) -> RefInfo|None:
    if not isinstance(object_type, str):
        object_type = get_object_type(object_type)
    return _JSON_REF_INFO.get(object_type, {}).get(json_field_name)

_LEGAL_FIELDS = {
    'circuits.circuit': frozenset(['assignments', 'cid', 'comments', 'commit_rate', 'custom_fields', 'description', 'distance', 'distance_unit', 'install_date', 'provider', 'provider_account', 'status', 'tags', 'tenant', 'termination_date', 'type']),
    'circuits.circuitgroup': frozenset(['custom_fields', 'description', 'name', 'slug', 'tags', 'tenant']),
    'circuits.circuitgroupassignment': frozenset(['group', 'member_id', 'member_type', 'priority', 'tags']),
    'circuits.circuittermination': frozenset(['circuit', 'custom_fields', 'description', 'mark_connected', 'port_speed', 'pp_info', 'tags', 'term_side', 'termination_id', 'termination_type', 'upstream_speed', 'xconnect_id']),
    'circuits.circuittype': frozenset(['color', 'custom_fields', 'description', 'name', 'slug', 'tags']),
    'circuits.provider': frozenset(['accounts', 'asns', 'comments', 'custom_fields', 'description', 'name', 'slug', 'tags']),
    'circuits.provideraccount': frozenset(['account', 'comments', 'custom_fields', 'description', 'name', 'provider', 'tags']),
    'circuits.providernetwork': frozenset(['comments', 'custom_fields', 'description', 'name', 'provider', 'service_id', 'tags']),
    'circuits.virtualcircuit': frozenset(['cid', 'comments', 'custom_fields', 'description', 'provider_account', 'provider_network', 'status', 'tags', 'tenant', 'type']),
    'circuits.virtualcircuittermination': frozenset(['custom_fields', 'description', 'interface', 'role', 'tags', 'virtual_circuit']),
    'circuits.virtualcircuittype': frozenset(['color', 'custom_fields', 'description', 'name', 'slug', 'tags']),
    'dcim.cable': frozenset(['a_terminations', 'b_terminations', 'color', 'comments', 'custom_fields', 'description', 'label', 'length', 'length_unit', 'status', 'tags', 'tenant', 'type']),
    'dcim.cablepath': frozenset(['is_active', 'is_complete', 'is_split']),
    'dcim.cabletermination': frozenset(['cable', 'cable_end', 'termination_id', 'termination_type']),
    'dcim.consoleport': frozenset(['custom_fields', 'description', 'device', 'label', 'mark_connected', 'module', 'name', 'speed', 'tags', 'type']),
    'dcim.consoleserverport': frozenset(['custom_fields', 'description', 'device', 'label', 'mark_connected', 'module', 'name', 'speed', 'tags', 'type']),
    'dcim.device': frozenset(['airflow', 'asset_tag', 'cluster', 'comments', 'custom_fields', 'description', 'device_type', 'face', 'latitude', 'location', 'longitude', 'name', 'oob_ip', 'platform', 'position', 'primary_ip4', 'primary_ip6', 'rack', 'role', 'serial', 'site', 'status', 'tags', 'tenant', 'vc_position', 'vc_priority', 'virtual_chassis']),
    'dcim.devicebay': frozenset(['custom_fields', 'description', 'device', 'installed_device', 'label', 'name', 'tags']),
    'dcim.devicerole': frozenset(['color', 'custom_fields', 'description', 'name', 'slug', 'tags', 'vm_role']),
    'dcim.devicetype': frozenset(['airflow', 'comments', 'custom_fields', 'default_platform', 'description', 'exclude_from_utilization', 'is_full_depth', 'manufacturer', 'model', 'part_number', 'slug', 'subdevice_role', 'tags', 'u_height', 'weight', 'weight_unit']),
    'dcim.frontport': frozenset(['color', 'custom_fields', 'description', 'device', 'label', 'mark_connected', 'module', 'name', 'rear_port', 'rear_port_position', 'tags', 'type']),
    'dcim.interface': frozenset(['bridge', 'custom_fields', 'description', 'device', 'duplex', 'enabled', 'label', 'lag', 'mark_connected', 'mgmt_only', 'mode', 'module', 'mtu', 'name', 'parent', 'poe_mode', 'poe_type', 'primary_mac_address', 'qinq_svlan', 'rf_channel', 'rf_channel_frequency', 'rf_channel_width', 'rf_role', 'speed', 'tagged_vlans', 'tags', 'tx_power', 'type', 'untagged_vlan', 'vdcs', 'vlan_translation_policy', 'vrf', 'wireless_lans', 'wwn']),
    'dcim.inventoryitem': frozenset(['asset_tag', 'component_id', 'component_type', 'custom_fields', 'description', 'device', 'discovered', 'label', 'manufacturer', 'name', 'parent', 'part_id', 'role', 'serial', 'status', 'tags']),
    'dcim.inventoryitemrole': frozenset(['color', 'custom_fields', 'description', 'name', 'slug', 'tags']),
    'dcim.location': frozenset(['custom_fields', 'description', 'facility', 'name', 'parent', 'site', 'slug', 'status', 'tags', 'tenant']),
    'dcim.macaddress': frozenset(['assigned_object_id', 'assigned_object_type', 'comments', 'custom_fields', 'description', 'mac_address', 'tags']),
    'dcim.manufacturer': frozenset(['custom_fields', 'description', 'name', 'slug', 'tags']),
    'dcim.module': frozenset(['asset_tag', 'comments', 'custom_fields', 'description', 'device', 'module_bay', 'module_type', 'serial', 'status', 'tags']),
    'dcim.modulebay': frozenset(['custom_fields', 'description', 'device', 'installed_module', 'label', 'module', 'name', 'position', 'tags']),
    'dcim.moduletype': frozenset(['airflow', 'comments', 'custom_fields', 'description', 'manufacturer', 'model', 'part_number', 'tags', 'weight', 'weight_unit']),
    'dcim.platform': frozenset(['custom_fields', 'description', 'manufacturer', 'name', 'slug', 'tags']),
    'dcim.powerfeed': frozenset(['amperage', 'comments', 'custom_fields', 'description', 'mark_connected', 'max_utilization', 'name', 'phase', 'power_panel', 'rack', 'status', 'supply', 'tags', 'tenant', 'type', 'voltage']),
    'dcim.poweroutlet': frozenset(['color', 'custom_fields', 'description', 'device', 'feed_leg', 'label', 'mark_connected', 'module', 'name', 'power_port', 'tags', 'type']),
    'dcim.powerpanel': frozenset(['comments', 'custom_fields', 'description', 'location', 'name', 'site', 'tags']),
    'dcim.powerport': frozenset(['allocated_draw', 'custom_fields', 'description', 'device', 'label', 'mark_connected', 'maximum_draw', 'module', 'name', 'tags', 'type']),
    'dcim.rack': frozenset(['airflow', 'asset_tag', 'comments', 'custom_fields', 'desc_units', 'description', 'facility_id', 'form_factor', 'location', 'max_weight', 'mounting_depth', 'name', 'outer_depth', 'outer_unit', 'outer_width', 'rack_type', 'role', 'serial', 'site', 'starting_unit', 'status', 'tags', 'tenant', 'u_height', 'weight', 'weight_unit', 'width']),
    'dcim.rackreservation': frozenset(['comments', 'custom_fields', 'description', 'rack', 'tags', 'tenant', 'units']),
    'dcim.rackrole': frozenset(['color', 'custom_fields', 'description', 'name', 'slug', 'tags']),
    'dcim.racktype': frozenset(['comments', 'custom_fields', 'desc_units', 'description', 'form_factor', 'manufacturer', 'max_weight', 'model', 'mounting_depth', 'outer_depth', 'outer_unit', 'outer_width', 'slug', 'starting_unit', 'tags', 'u_height', 'weight', 'weight_unit', 'width']),
    'dcim.rearport': frozenset(['color', 'custom_fields', 'description', 'device', 'label', 'mark_connected', 'module', 'name', 'positions', 'tags', 'type']),
    'dcim.region': frozenset(['custom_fields', 'description', 'name', 'parent', 'slug', 'tags']),
    'dcim.site': frozenset(['asns', 'comments', 'custom_fields', 'description', 'facility', 'group', 'latitude', 'longitude', 'name', 'physical_address', 'region', 'shipping_address', 'slug', 'status', 'tags', 'tenant', 'time_zone']),
    'dcim.sitegroup': frozenset(['custom_fields', 'description', 'name', 'parent', 'slug', 'tags']),
    'dcim.virtualchassis': frozenset(['comments', 'custom_fields', 'description', 'domain', 'master', 'name', 'tags']),
    'dcim.virtualdevicecontext': frozenset(['comments', 'custom_fields', 'description', 'device', 'identifier', 'name', 'primary_ip4', 'primary_ip6', 'status', 'tags', 'tenant']),
    'extras.tag': frozenset(['color', 'name', 'slug']),
    'ipam.aggregate': frozenset(['comments', 'custom_fields', 'date_added', 'description', 'prefix', 'rir', 'tags', 'tenant']),
    'ipam.asn': frozenset(['asn', 'comments', 'custom_fields', 'description', 'rir', 'tags', 'tenant']),
    'ipam.asnrange': frozenset(['custom_fields', 'description', 'end', 'name', 'rir', 'slug', 'start', 'tags', 'tenant']),
    'ipam.fhrpgroup': frozenset(['auth_key', 'auth_type', 'comments', 'custom_fields', 'description', 'group_id', 'name', 'protocol', 'tags']),
    'ipam.fhrpgroupassignment': frozenset(['group', 'interface_id', 'interface_type', 'priority']),
    'ipam.ipaddress': frozenset(['address', 'assigned_object_id', 'assigned_object_type', 'comments', 'custom_fields', 'description', 'dns_name', 'nat_inside', 'role', 'status', 'tags', 'tenant', 'vrf']),
    'ipam.iprange': frozenset(['comments', 'custom_fields', 'description', 'end_address', 'mark_utilized', 'role', 'start_address', 'status', 'tags', 'tenant', 'vrf']),
    'ipam.prefix': frozenset(['comments', 'custom_fields', 'description', 'is_pool', 'mark_utilized', 'prefix', 'role', 'scope_id', 'scope_type', 'status', 'tags', 'tenant', 'vlan', 'vrf']),
    'ipam.rir': frozenset(['custom_fields', 'description', 'is_private', 'name', 'slug', 'tags']),
    'ipam.role': frozenset(['custom_fields', 'description', 'name', 'slug', 'tags', 'weight']),
    'ipam.routetarget': frozenset(['comments', 'custom_fields', 'description', 'name', 'tags', 'tenant']),
    'ipam.service': frozenset(['comments', 'custom_fields', 'description', 'device', 'ipaddresses', 'name', 'ports', 'protocol', 'tags', 'virtual_machine']),
    'ipam.vlan': frozenset(['comments', 'custom_fields', 'description', 'group', 'name', 'qinq_role', 'qinq_svlan', 'role', 'site', 'status', 'tags', 'tenant', 'vid']),
    'ipam.vlangroup': frozenset(['custom_fields', 'description', 'name', 'scope_id', 'scope_type', 'slug', 'tags', 'vid_ranges']),
    'ipam.vlantranslationpolicy': frozenset(['description', 'name']),
    'ipam.vlantranslationrule': frozenset(['description', 'local_vid', 'policy', 'remote_vid']),
    'ipam.vrf': frozenset(['comments', 'custom_fields', 'description', 'enforce_unique', 'export_targets', 'import_targets', 'name', 'rd', 'tags', 'tenant']),
    'tenancy.contact': frozenset(['address', 'comments', 'custom_fields', 'description', 'email', 'group', 'link', 'name', 'phone', 'tags', 'title']),
    'tenancy.contactassignment': frozenset(['contact', 'custom_fields', 'object_id', 'object_type', 'priority', 'role', 'tags']),
    'tenancy.contactgroup': frozenset(['custom_fields', 'description', 'name', 'parent', 'slug', 'tags']),
    'tenancy.contactrole': frozenset(['custom_fields', 'description', 'name', 'slug', 'tags']),
    'tenancy.tenant': frozenset(['comments', 'custom_fields', 'description', 'group', 'name', 'slug', 'tags']),
    'tenancy.tenantgroup': frozenset(['custom_fields', 'description', 'name', 'parent', 'slug', 'tags']),
    'virtualization.cluster': frozenset(['comments', 'custom_fields', 'description', 'group', 'name', 'scope_id', 'scope_type', 'status', 'tags', 'tenant', 'type']),
    'virtualization.clustergroup': frozenset(['custom_fields', 'description', 'name', 'slug', 'tags']),
    'virtualization.clustertype': frozenset(['custom_fields', 'description', 'name', 'slug', 'tags']),
    'virtualization.virtualdisk': frozenset(['custom_fields', 'description', 'name', 'size', 'tags', 'virtual_machine']),
    'virtualization.virtualmachine': frozenset(['cluster', 'comments', 'custom_fields', 'description', 'device', 'disk', 'memory', 'name', 'platform', 'primary_ip4', 'primary_ip6', 'role', 'serial', 'site', 'status', 'tags', 'tenant', 'vcpus']),
    'virtualization.vminterface': frozenset(['bridge', 'custom_fields', 'description', 'enabled', 'mode', 'mtu', 'name', 'parent', 'primary_mac_address', 'qinq_svlan', 'tagged_vlans', 'tags', 'untagged_vlan', 'virtual_machine', 'vlan_translation_policy', 'vrf']),
    'vpn.ikepolicy': frozenset(['comments', 'custom_fields', 'description', 'mode', 'name', 'preshared_key', 'proposals', 'tags', 'version']),
    'vpn.ikeproposal': frozenset(['authentication_algorithm', 'authentication_method', 'comments', 'custom_fields', 'description', 'encryption_algorithm', 'group', 'name', 'sa_lifetime', 'tags']),
    'vpn.ipsecpolicy': frozenset(['comments', 'custom_fields', 'description', 'name', 'pfs_group', 'proposals', 'tags']),
    'vpn.ipsecprofile': frozenset(['comments', 'custom_fields', 'description', 'ike_policy', 'ipsec_policy', 'mode', 'name', 'tags']),
    'vpn.ipsecproposal': frozenset(['authentication_algorithm', 'comments', 'custom_fields', 'description', 'encryption_algorithm', 'name', 'sa_lifetime_data', 'sa_lifetime_seconds', 'tags']),
    'vpn.l2vpn': frozenset(['comments', 'custom_fields', 'description', 'export_targets', 'identifier', 'import_targets', 'name', 'slug', 'tags', 'tenant', 'type']),
    'vpn.l2vpntermination': frozenset(['assigned_object_id', 'assigned_object_type', 'custom_fields', 'l2vpn', 'tags']),
    'vpn.tunnel': frozenset(['comments', 'custom_fields', 'description', 'encapsulation', 'group', 'ipsec_profile', 'name', 'status', 'tags', 'tenant', 'tunnel_id']),
    'vpn.tunnelgroup': frozenset(['custom_fields', 'description', 'name', 'slug', 'tags']),
    'vpn.tunneltermination': frozenset(['custom_fields', 'outside_ip', 'role', 'tags', 'termination_id', 'termination_type', 'tunnel']),
    'wireless.wirelesslan': frozenset(['auth_cipher', 'auth_psk', 'auth_type', 'comments', 'custom_fields', 'description', 'group', 'scope_id', 'scope_type', 'ssid', 'status', 'tags', 'tenant', 'vlan']),
    'wireless.wirelesslangroup': frozenset(['custom_fields', 'description', 'name', 'parent', 'slug', 'tags']),
    'wireless.wirelesslink': frozenset(['auth_cipher', 'auth_psk', 'auth_type', 'comments', 'custom_fields', 'description', 'distance', 'distance_unit', 'interface_a', 'interface_b', 'ssid', 'status', 'tags', 'tenant']),
}

def legal_fields(object_type: str|Type[models.Model]) -> frozenset[str]:
    if not isinstance(object_type, str):
        object_type = get_object_type(object_type)
    return _LEGAL_FIELDS.get(object_type, frozenset())

_OBJECT_TYPE_PRIMARY_VALUE_FIELD_MAP = {
    'ipam.asn': 'asn',
    'dcim.devicetype': 'model',
    'circuits.circuit': 'cid',
    'ipam.ipaddress': 'address',
    'dcim.macaddress': 'mac_address',
    'dcim.moduletype': 'model',
    'ipam.prefix': 'prefix',
    'dcim.racktype': 'model',
    'circuits.virtualcircuit': 'cid',
    'wireless.wirelesslan': 'ssid',
}

def get_primary_value(data: dict, object_type: str) -> str|None:
    field = _OBJECT_TYPE_PRIMARY_VALUE_FIELD_MAP.get(object_type, 'name')
    return data.get(field)