---
name: ✨ Feature Request
description: Propose a new Diode NetBox Plugin feature or enhancement
labels: ["enhancement", "status: needs triage"]
body:
  - type: input
    attributes:
      label: Diode NetBox Plugin version
      description: What version of Diode NetBox Plugin are you currently running?
      placeholder: v0.6.0
    validations:
      required: true
  - type: input
    attributes:
      label: NetBox version
      description: What version of NetBox are you currently running?
      placeholder: v4.1.3
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Feature type
      options:
        - New functionality
        - Change to existing functionality
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed feature or enhancement
      description: >
        Describe in detail the new feature or enhancement you are proposing. The more detail you provide here, 
        the greater chance your proposal has of being discussed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: >
        Explain how adding this feature or enhancement would benefit Diode users. What need does it address?
    validations:
      required: true
