FROM netboxcommunity/netbox:v4.3.3-3.3.0

COPY ./netbox/configuration/ /etc/netbox/config/
RUN chmod 755 /etc/netbox/config/* && \
    chown unit:root /etc/netbox/config/*

COPY ./netbox/local_settings.py /opt/netbox/netbox/netbox/local_settings.py
RUN chmod 755 /opt/netbox/netbox/netbox/local_settings.py && \
    chown unit:root /opt/netbox/netbox/netbox/local_settings.py

COPY ./requirements-diode-netbox-plugin.txt /opt/netbox/
ENV VIRTUAL_ENV=/opt/netbox/venv
RUN /usr/local/bin/uv pip install -r /opt/netbox/requirements-diode-netbox-plugin.txt
