# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from netbox_diode_plugin.reconciler.sdk.v1 import reconciler_pb2 as diode_dot_v1_dot_reconciler__pb2


class ReconcilerServiceStub(object):
    """Reconciler service API
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RetrieveIngestionLogs = channel.unary_unary(
                '/diode.v1.ReconcilerService/RetrieveIngestionLogs',
                request_serializer=diode_dot_v1_dot_reconciler__pb2.RetrieveIngestionLogsRequest.SerializeToString,
                response_deserializer=diode_dot_v1_dot_reconciler__pb2.RetrieveIngestionLogsResponse.FromString,
                )
        self.RetrieveDeviations = channel.unary_unary(
                '/diode.v1.ReconcilerService/RetrieveDeviations',
                request_serializer=diode_dot_v1_dot_reconciler__pb2.RetrieveDeviationsRequest.SerializeToString,
                response_deserializer=diode_dot_v1_dot_reconciler__pb2.RetrieveDeviationsResponse.FromString,
                )
        self.RetrieveDeviationByID = channel.unary_unary(
                '/diode.v1.ReconcilerService/RetrieveDeviationByID',
                request_serializer=diode_dot_v1_dot_reconciler__pb2.RetrieveDeviationByIDRequest.SerializeToString,
                response_deserializer=diode_dot_v1_dot_reconciler__pb2.RetrieveDeviationByIDResponse.FromString,
                )


class ReconcilerServiceServicer(object):
    """Reconciler service API
    """

    def RetrieveIngestionLogs(self, request, context):
        """Retrieves ingestion logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveDeviations(self, request, context):
        """Retrieve deviations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveDeviationByID(self, request, context):
        """Retrieve deviation by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReconcilerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RetrieveIngestionLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveIngestionLogs,
                    request_deserializer=diode_dot_v1_dot_reconciler__pb2.RetrieveIngestionLogsRequest.FromString,
                    response_serializer=diode_dot_v1_dot_reconciler__pb2.RetrieveIngestionLogsResponse.SerializeToString,
            ),
            'RetrieveDeviations': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveDeviations,
                    request_deserializer=diode_dot_v1_dot_reconciler__pb2.RetrieveDeviationsRequest.FromString,
                    response_serializer=diode_dot_v1_dot_reconciler__pb2.RetrieveDeviationsResponse.SerializeToString,
            ),
            'RetrieveDeviationByID': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveDeviationByID,
                    request_deserializer=diode_dot_v1_dot_reconciler__pb2.RetrieveDeviationByIDRequest.FromString,
                    response_serializer=diode_dot_v1_dot_reconciler__pb2.RetrieveDeviationByIDResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'diode.v1.ReconcilerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReconcilerService(object):
    """Reconciler service API
    """

    @staticmethod
    def RetrieveIngestionLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/diode.v1.ReconcilerService/RetrieveIngestionLogs',
            diode_dot_v1_dot_reconciler__pb2.RetrieveIngestionLogsRequest.SerializeToString,
            diode_dot_v1_dot_reconciler__pb2.RetrieveIngestionLogsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveDeviations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/diode.v1.ReconcilerService/RetrieveDeviations',
            diode_dot_v1_dot_reconciler__pb2.RetrieveDeviationsRequest.SerializeToString,
            diode_dot_v1_dot_reconciler__pb2.RetrieveDeviationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveDeviationByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/diode.v1.ReconcilerService/RetrieveDeviationByID',
            diode_dot_v1_dot_reconciler__pb2.RetrieveDeviationByIDRequest.SerializeToString,
            diode_dot_v1_dot_reconciler__pb2.RetrieveDeviationByIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
